/*
* This header is generated by classdump-dyld 0.7
* on Tuesday, September 15, 2015 at 5:29:41 PM Central Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /var/mobile/Containers/Bundle/Application/78EC956B-7ED8-4B50-8025-C2B1976EEC28/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSString;

@interface CountryData : NSObject {

	NSString* _name;
	NSString* _number;

}

@property (nonatomic,copy) NSString * name;                //@synthesize name=_name - In the implementation block
@property (nonatomic,copy) NSString * number;              //@synthesize number=_number - In the implementation block
-(void)setName:(NSString *)arg1 ;
-(NSString *)name;
-(void)setNumber:(NSString *)arg1 ;
-(NSString *)number;
@end

