/*
* This header is generated by classdump-dyld 0.7
* on Tuesday, February 2, 2016 at 7:26:29 PM Central Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3AACC7FB-0FE9-4871-925D-3A035BF7F4E1/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSString;

@interface CountryData : NSObject {

	NSString* _name;
	NSString* _number;

}

@property (nonatomic,copy) NSString * name;                //@synthesize name=_name - In the implementation block
@property (nonatomic,copy) NSString * number;              //@synthesize number=_number - In the implementation block
-(void)setName:(NSString *)arg1 ;
-(NSString *)name;
-(NSString *)number;
-(void)setNumber:(NSString *)arg1 ;
@end

