/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 26, 2016 at 3:43:39 PM Central Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /private/var/mobile/Containers/Bundle/Application/5A2897A0-78CA-4D27-9EEF-4F1B698EB436/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Instagram/CPTAnnotation.h>

@class CPTLayer, CPTConstraints;

@interface CPTLayerAnnotation : CPTAnnotation {

	CPTLayer* anchorLayer;
	int rectAnchor;
	CPTConstraints* xConstraints;
	CPTConstraints* yConstraints;

}

@property (nonatomic,__weak,readonly) CPTLayer * anchorLayer; 
@property (assign,nonatomic) int rectAnchor; 
@property (nonatomic,retain) CPTConstraints * xConstraints; 
@property (nonatomic,retain) CPTConstraints * yConstraints; 
-(void)positionContentLayer;
-(id)initWithAnchorLayer:(id)arg1 ;
-(void)setRectAnchor:(int)arg1 ;
-(CPTLayer *)anchorLayer;
-(CPTConstraints *)xConstraints;
-(CPTConstraints *)yConstraints;
-(int)rectAnchor;
-(void)setXConstraints:(CPTConstraints *)arg1 ;
-(void)setYConstraints:(CPTConstraints *)arg1 ;
-(void)setConstraints;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(void)dealloc;
-(id)init;
@end

