/*
* This header is generated by classdump-dyld 0.7
* on Tuesday, January 19, 2016 at 3:15:03 PM Central Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/4DC55608-3697-420B-B226-BE8BA2A1BD0A/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Instagram/Instagram-Structs.h>
#import <Instagram/CPTNumericData.h>

@class NSArray;

@interface CPTMutableNumericData : CPTNumericData

@property (assign,nonatomic) CPTNumericDataType dataType; 
@property (assign,nonatomic) int dataTypeFormat; 
@property (assign,nonatomic) unsigned long sampleBytes; 
@property (assign,nonatomic) long byteOrder; 
@property (nonatomic,readonly) void* mutableBytes; 
@property (nonatomic,copy) NSArray * shape; 
-(void)convertToType:(int)arg1 sampleBytes:(unsigned long)arg2 byteOrder:(long)arg3 ;
-(void)setDataTypeFormat:(int)arg1 ;
-(void)setSampleBytes:(unsigned long)arg1 ;
-(void)setByteOrder:(long)arg1 ;
-(void*)mutableSamplePointer:(unsigned)arg1 ;
-(void*)mutableSamplePointerAtIndex:(unsigned)arg1 ;
-(void*)mutableBytes;
@end

