/*
* This header is generated by classdump-dyld 1.0
* on Friday, May 13, 2016 at 9:28:38 PM Central Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/6C2D6691-0360-45BF-8623-49F0546803FE/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Instagram/CPTTextStyle.h>

@class NSString, CPTColor;

@interface CPTMutableTextStyle : CPTTextStyle

@property (nonatomic,copy) NSString * fontName; 
@property (assign,nonatomic) float fontSize; 
@property (nonatomic,copy) CPTColor * color; 
@property (assign,nonatomic) int textAlignment; 
@property (assign,nonatomic) int lineBreakMode; 
+(id)textStyleWithAttributes:(id)arg1 ;
@end

