/*
* This header is generated by classdump-dyld 1.0
* on Monday, February 29, 2016 at 3:36:53 PM Central Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/8E0CB1D4-3D23-4350-ABAD-ADD1AC46A9D0/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Instagram/Instagram-Structs.h>
#import <Instagram/CPTAnnotation.h>

@class NSArray, CPTPlotSpace;

@interface CPTPlotSpaceAnnotation : CPTAnnotation {

	NSArray* anchorPlotPoint;
	CPTPlotSpace* plotSpace;
	SCD_Struct_CP79* decimalAnchor;
	unsigned anchorCount;

}

@property (nonatomic,copy) NSArray * anchorPlotPoint; 
@property (nonatomic,readonly) CPTPlotSpace * plotSpace; 
@property (assign,nonatomic) SCD_Struct_CP79* decimalAnchor; 
@property (assign,nonatomic) unsigned anchorCount; 
-(void)positionContentLayer;
-(CPTPlotSpace *)plotSpace;
-(void)setAnchorPlotPoint:(NSArray *)arg1 ;
-(void)setContentNeedsLayout;
-(id)initWithPlotSpace:(id)arg1 anchorPlotPoint:(id)arg2 ;
-(NSArray *)anchorPlotPoint;
-(SCD_Struct_CP79*)decimalAnchor;
-(void)setAnchorCount:(unsigned)arg1 ;
-(void)setDecimalAnchor:(SCD_Struct_CP79*)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(void)dealloc;
-(id)init;
-(unsigned)anchorCount;
@end

