/*
* This header is generated by classdump-dyld 0.7
* on Tuesday, October 13, 2015 at 10:20:10 PM Central Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /var/mobile/Containers/Bundle/Application/095E6AAC-0201-41F1-901D-3BA0DA7A9B94/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSMutableDictionary, NSURL, NSString, NSDate;

@interface FBBreakpadCrashReport : NSObject {

	NSMutableDictionary* _parameters;
	NSURL* _exceptionURL;
	NSString* _minidumpPath;
	NSString* _configPath;
	NSString* _extraPath;
	NSDate* _crashTime;

}

@property (nonatomic,readonly) NSURL * exceptionURL;                      //@synthesize exceptionURL=_exceptionURL - In the implementation block
@property (nonatomic,copy,readonly) NSString * minidumpPath;              //@synthesize minidumpPath=_minidumpPath - In the implementation block
@property (nonatomic,copy,readonly) NSString * configPath;                //@synthesize configPath=_configPath - In the implementation block
@property (nonatomic,copy,readonly) NSString * extraPath;                 //@synthesize extraPath=_extraPath - In the implementation block
@property (nonatomic,readonly) NSDate * crashTime;                        //@synthesize crashTime=_crashTime - In the implementation block
+(double)defaultSendCrashReportTimeoutInterval;
-(id)minidumpData;
-(char)loadConfigFile:(id)arg1 errorHandler:(/*^block*/id)arg2 ;
-(id)sendCrashReport:(id*)arg1 timeoutInterval:(double)arg2 ;
-(id)readExtraData:(const char*)arg1 ;
-(id)readDataFromFile:(int)arg1 withLength:(long)arg2 ;
-(void)addParameter:(id)arg1 forKey:(id)arg2 ;
-(NSURL *)exceptionURL;
-(NSString *)minidumpPath;
-(NSString *)extraPath;
-(id)sendCrashReport:(id*)arg1 ;
-(id)initWithConfigPath:(id)arg1 errorHandler:(/*^block*/id)arg2 ;
-(NSDate *)crashTime;
-(void)cleanupFiles;
-(NSString *)configPath;
-(void)removeParameterForKey:(id)arg1 ;
-(id)parameters;
-(id)readString:(int)arg1 ;
@end

