/*
* This header is generated by classdump-dyld 0.7
* on Thursday, August 27, 2015 at 8:51:38 PM Central Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /var/mobile/Containers/Bundle/Application/2DC1EEC6-8BB6-4C9F-8658-A819865606D1/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Instagram/Instagram-Structs.h>
#import <Instagram/FBDialogsParams.h>

@class NSString;

@interface FBLikeDialogParams : FBDialogsParams {

	NSString* _objectID;

}

@property (nonatomic,copy) NSString * objectID;              //@synthesize objectID=_objectID - In the implementation block
+(id)methodName;
-(id)dictionaryMethodArgs;
-(void)dealloc;
-(id)validate;
-(id)copyWithZone:(NSZone*)arg1 ;
-(NSString *)objectID;
-(void)setObjectID:(NSString *)arg1 ;
@end

