/*
* This header is generated by classdump-dyld 1.0
* on Friday, May 13, 2016 at 9:28:38 PM Central Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/6C2D6691-0360-45BF-8623-49F0546803FE/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface FBSDKLoginError : NSObject
+(id)errorFromReturnURLParameters:(id)arg1 ;
+(id)errorFromServerError:(id)arg1 ;
+(id)errorForSystemPasswordChange:(id)arg1 ;
+(id)errorForSystemAccountStoreError:(id)arg1 ;
+(id)errorForFailedLoginWithCode:(int)arg1 innerError:(id)arg2 ;
+(id)errorWithSystemAccountStoreDeniedError:(id)arg1 isCancellation:(char*)arg2 ;
+(id)errorForFailedLoginWithCode:(int)arg1 ;
+(id)errorDomain;
-(id)init;
@end

