/*
* This header is generated by classdump-dyld 0.7
* on Tuesday, January 19, 2016 at 3:15:04 PM Central Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/4DC55608-3697-420B-B226-BE8BA2A1BD0A/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Instagram/Instagram-Structs.h>
#import <libobjc.A.dylib/NSCopying.h>
#import <libobjc.A.dylib/NSSecureCoding.h>

@class NSString, NSArray;

@interface FBSDKErrorRecoveryConfiguration : NSObject <NSCopying, NSSecureCoding> {

	NSString* _localizedRecoveryDescription;
	NSArray* _localizedRecoveryOptionDescriptions;
	unsigned _errorCategory;
	NSString* _recoveryActionName;

}

@property (nonatomic,readonly) NSString * localizedRecoveryDescription;                    //@synthesize localizedRecoveryDescription=_localizedRecoveryDescription - In the implementation block
@property (nonatomic,readonly) NSArray * localizedRecoveryOptionDescriptions;              //@synthesize localizedRecoveryOptionDescriptions=_localizedRecoveryOptionDescriptions - In the implementation block
@property (nonatomic,readonly) unsigned errorCategory;                                     //@synthesize errorCategory=_errorCategory - In the implementation block
@property (nonatomic,readonly) NSString * recoveryActionName;                              //@synthesize recoveryActionName=_recoveryActionName - In the implementation block
+(char)supportsSecureCoding;
-(unsigned)errorCategory;
-(NSString *)recoveryActionName;
-(id)initWithRecoveryDescription:(id)arg1 optionDescriptions:(id)arg2 category:(unsigned)arg3 recoveryActionName:(id)arg4 ;
-(NSString *)localizedRecoveryDescription;
-(NSArray *)localizedRecoveryOptionDescriptions;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(id)init;
-(id)copyWithZone:(NSZone*)arg1 ;
@end

