/*
* This header is generated by classdump-dyld 1.0
* on Monday, April 11, 2016 at 7:42:02 PM Central Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /private/var/mobile/Containers/Bundle/Application/F2F7650E-6416-4D13-A52F-83DEE7C62D71/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMutableDictionary, FBSDKAccessToken, NSSet, NSDictionary;

@interface FBSDKLoginManagerLoginResult : NSObject {

	NSMutableDictionary* _mutableLoggingExtras;
	char _isCancelled;
	char _isSkipped;
	FBSDKAccessToken* _token;
	NSSet* _grantedPermissions;
	NSSet* _declinedPermissions;

}

@property (nonatomic,copy) FBSDKAccessToken * token;                      //@synthesize token=_token - In the implementation block
@property (nonatomic,readonly) char isCancelled;                          //@synthesize isCancelled=_isCancelled - In the implementation block
@property (nonatomic,copy) NSSet * grantedPermissions;                    //@synthesize grantedPermissions=_grantedPermissions - In the implementation block
@property (nonatomic,copy) NSSet * declinedPermissions;                   //@synthesize declinedPermissions=_declinedPermissions - In the implementation block
@property (nonatomic,readonly) NSDictionary * loggingExtras; 
@property (assign,nonatomic) char isSkipped;                              //@synthesize isSkipped=_isSkipped - In the implementation block
-(NSDictionary *)loggingExtras;
-(NSSet *)declinedPermissions;
-(void)setDeclinedPermissions:(NSSet *)arg1 ;
-(char)isSkipped;
-(id)initWithToken:(id)arg1 isCancelled:(char)arg2 grantedPermissions:(id)arg3 declinedPermissions:(id)arg4 ;
-(void)addLoggingExtra:(id)arg1 forKey:(id)arg2 ;
-(void)setIsSkipped:(char)arg1 ;
-(id)init;
-(char)isCancelled;
-(FBSDKAccessToken *)token;
-(void)setToken:(FBSDKAccessToken *)arg1 ;
-(NSSet *)grantedPermissions;
-(void)setGrantedPermissions:(NSSet *)arg1 ;
@end

