/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 13, 2015 at 8:04:12 PM Central Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/80FB49E7-07A3-4438-9519-37CDCDE82DE6/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface FBWebDialogs : NSObject
+(void)presentDialogModallyWithSession:(id)arg1 dialog:(id)arg2 parameters:(id)arg3 handler:(/*^block*/id)arg4 delegate:(id)arg5 ;
+(void)presentRequestsDialogModallyWithSession:(id)arg1 message:(id)arg2 title:(id)arg3 parameters:(id)arg4 handler:(/*^block*/id)arg5 friendCache:(id)arg6 ;
+(void)presentDialogModallyWithSession:(id)arg1 dialog:(id)arg2 parameters:(id)arg3 handler:(/*^block*/id)arg4 ;
+(void)presentRequestsDialogModallyWithSession:(id)arg1 message:(id)arg2 title:(id)arg3 parameters:(id)arg4 handler:(/*^block*/id)arg5 ;
+(void)presentFeedDialogModallyWithSession:(id)arg1 parameters:(id)arg2 handler:(/*^block*/id)arg3 ;
@end

