/*
* This header is generated by classdump-dyld 0.7
* on Tuesday, February 2, 2016 at 7:26:38 PM Central Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3AACC7FB-0FE9-4871-925D-3A035BF7F4E1/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol FBWebViewAnalytics;
@class NSMutableArray, WKProcessPool;

@interface FBWKProcessPool : NSObject {

	NSMutableArray* _completionHandlers;
	id<FBWebViewAnalytics> _analytics;
	char _initialized;
	char _invalidated;
	WKProcessPool* _wkProcessPool;

}

@property (nonatomic,readonly) WKProcessPool * wkProcessPool;              //@synthesize wkProcessPool=_wkProcessPool - In the implementation block
+(id)wkProcessPoolForContainer:(id)arg1 analytics:(id)arg2 completionHandler:(/*^block*/id)arg3 ;
-(WKProcessPool *)wkProcessPool;
-(id)init;
-(void)invalidate;
-(void)addCompletionHandler:(/*^block*/id)arg1 ;
@end

