/*
* This header is generated by classdump-dyld 0.7
* on Tuesday, February 2, 2016 at 7:26:35 PM Central Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3AACC7FB-0FE9-4871-925D-3A035BF7F4E1/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSString, NSData;

@interface FileUploadAttachment : NSObject {

	NSString* _filename;
	NSString* _name;
	NSString* _contentType;
	NSString* _filePath;
	NSData* _contents;

}
-(id)initWithFilename:(id)arg1 name:(id)arg2 contentType:(id)arg3 filePath:(id)arg4 contents:(id)arg5 ;
-(id)initWithFilename:(id)arg1 name:(id)arg2 contents:(id)arg3 shouldCompress:(char)arg4 ;
-(id)name;
-(id)contents;
-(id)contentType;
-(id)filePath;
-(id)filename;
@end

