/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 13, 2015 at 8:04:08 PM Central Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/80FB49E7-07A3-4438-9519-37CDCDE82DE6/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Instagram/Instagram-Structs.h>
#import <Instagram/TBaseStruct.h>

@class NSString, NSNumber;

@interface HoneySchema : TBaseStruct {

	NSString* __thrift_sessionID;
	NSNumber* __thrift_seq;

}
-(id)toDict;
-(id)initWithSessionID:(id)arg1 seq:(id)arg2 ;
-(id)init;
-(id)description;
-(id)mutableCopyWithZone:(NSZone*)arg1 ;
-(void)write:(id)arg1 ;
@end

