/*
* This header is generated by classdump-dyld 1.0
* on Friday, May 13, 2016 at 9:28:35 PM Central Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/6C2D6691-0360-45BF-8623-49F0546803FE/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <Instagram/Instagram-Structs.h>
@class NSMutableArray;

@interface IGAnalyticsMetadata : NSObject {

	NSMutableArray* _navStack;
	NSMutableArray* _analyticsNavStack;

}

@property (nonatomic,retain) NSMutableArray * navStack;                       //@synthesize navStack=_navStack - In the implementation block
@property (nonatomic,retain) NSMutableArray * analyticsNavStack;              //@synthesize analyticsNavStack=_analyticsNavStack - In the implementation block
-(void)setNavStack:(NSMutableArray *)arg1 ;
-(void)setAnalyticsNavStack:(NSMutableArray *)arg1 ;
-(NSMutableArray *)navStack;
-(id)currentNavEvent;
-(NSMutableArray *)analyticsNavStack;
-(id)currentAnalyticsNavEvent;
-(void)pushNavEvent:(id)arg1 ;
-(void)pushAnalyticsNavEvent:(id)arg1 ;
-(id)popNavEvent;
-(id)popAnalyticsNavEvent;
-(void)pushAnalyticsMetadataForViewController:(id)arg1 ;
-(void)popAnalyticsMetadataForViewController:(id)arg1 ;
-(id)newNavState;
-(id)newAnalyticsNavState;
-(id)init;
-(char)isEqual:(id)arg1 ;
-(unsigned)hash;
-(id)copyWithZone:(NSZone*)arg1 ;
@end

