/*
* This header is generated by classdump-dyld 0.7
* on Thursday, August 27, 2015 at 8:47:01 PM Central Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /var/mobile/Containers/Bundle/Application/2DC1EEC6-8BB6-4C9F-8658-A819865606D1/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSString, NSMutableDictionary;

@interface IGAnalyticsEvent : NSObject {

	NSString* _module;
	NSMutableDictionary* _extra;
	double _time;
	int _channel;
	NSString* _name;

}

@property (nonatomic,copy) NSString * name;              //@synthesize name=_name - In the implementation block
+(id)scheduleEvent:(id)arg1 ;
+(void)initializeAnalyticsOnce;
+(id)scheduleEvent:(id)arg1 module:(id)arg2 noLatency:(char)arg3 ;
+(void)incrementCounter:(id)arg1 byAmount:(int)arg2 ;
+(void)startTimer:(id)arg1 uuid:(id)arg2 ;
+(void)recordAverage:(id)arg1 value:(double)arg2 ;
+(void)recordEvent:(id)arg1 forTimer:(id)arg2 uuid:(id)arg3 ;
+(void)incrementCounter:(id)arg1 ;
+(void)startTimer:(id)arg1 ;
+(void)recordEvent:(id)arg1 forTimer:(id)arg2 ;
-(id)initWithName:(id)arg1 module:(id)arg2 channel:(int)arg3 ;
-(void)setValue:(id)arg1 forExtraKey:(id)arg2 ;
-(void)dealloc;
-(id)description;
-(id)objectForKeyedSubscript:(id)arg1 ;
-(void)setObject:(id)arg1 forKeyedSubscript:(id)arg2 ;
-(void)setName:(NSString *)arg1 ;
-(NSString *)name;
-(void)addEntriesFromDictionary:(id)arg1 ;
-(void)log;
@end

