/*
* This header is generated by classdump-dyld 1.0
* on Monday, April 11, 2016 at 7:41:44 PM Central Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /private/var/mobile/Containers/Bundle/Application/F2F7650E-6416-4D13-A52F-83DEE7C62D71/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Instagram/Instagram-Structs.h>
#import <QuartzCore/CALayer.h>

@class UIColor;

@interface IGArcLayer : CALayer {

	float _trackThickness;
	UIColor* _progressTintColor;
	UIColor* _trackTintColor;

}

@property (assign,nonatomic) float trackThickness;                     //@synthesize trackThickness=_trackThickness - In the implementation block
@property (nonatomic,retain) UIColor * progressTintColor;              //@synthesize progressTintColor=_progressTintColor - In the implementation block
@property (nonatomic,retain) UIColor * trackTintColor;                 //@synthesize trackTintColor=_trackTintColor - In the implementation block
@property (assign,nonatomic) float progress; 
+(char)needsDisplayForKey:(id)arg1 ;
-(void)setTrackThickness:(float)arg1 ;
-(float)trackThickness;
-(UIColor *)trackTintColor;
-(UIColor *)progressTintColor;
-(void)setProgressTintColor:(UIColor *)arg1 ;
-(void)setTrackTintColor:(UIColor *)arg1 ;
-(id)initWithLayer:(id)arg1 ;
-(void)drawInContext:(CGContextRef)arg1 ;
@end

