/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 13, 2015 at 8:03:49 PM Central Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/80FB49E7-07A3-4438-9519-37CDCDE82DE6/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSMutableDictionary, UIImage, CLLocation;

@interface IGAssetWriter : NSObject {

	NSMutableDictionary* _metadata;
	UIImage* _image;
	CLLocation* _location;

}

@property (nonatomic,retain) UIImage * image;                    //@synthesize image=_image - In the implementation block
@property (nonatomic,retain) CLLocation * location;              //@synthesize location=_location - In the implementation block
+(void)writeVideo:(id)arg1 toInstagramAlbum:(char)arg2 completionBlock:(/*^block*/id)arg3 ;
+(void)writeVideoToCameraRoll:(id)arg1 ;
+(void)writeVideoToInstagramAlbum:(id)arg1 completionBlock:(/*^block*/id)arg2 ;
-(id)initWithImage:(id)arg1 metadata:(id)arg2 ;
-(void)writeToInstagramAlbum;
-(void)writeToCameraRoll;
-(void)writeToInstagramAlbum:(char)arg1 ;
-(void)showLibraryAccessMessage;
-(void)setImage:(UIImage *)arg1 ;
-(id)init;
-(UIImage *)image;
-(CLLocation *)location;
-(void)setLocation:(CLLocation *)arg1 ;
@end

