/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 13, 2015 at 8:03:45 PM Central Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/80FB49E7-07A3-4438-9519-37CDCDE82DE6/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol IGAssetPlayerViewDelegate <NSObject>
@optional
-(void)assetPlayerViewAssetLoaded:(id)arg1;
-(void)assetPlayerViewPlayStateDidChange:(id)arg1;
-(void)assetPlayerView:(id)arg1 didPlayToTime:(SCD_Struct_IG0)arg2;

@end

