/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, February 16, 2016 at 3:16:02 PM Central Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/C13E072C-E6C1-44DA-8A86-89C97396B2E7/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <Instagram/Instagram-Structs.h>
@interface IGAssetMaker : NSObject
+(void)drawPath:(id)arg1 atPoint:(CGPoint)arg2 style:(id)arg3 inContext:(CGContextRef)arg4 ;
+(id)drawImageOfSize:(CGSize)arg1 opaque:(char)arg2 scale:(float)arg3 drawBlock:(/*^block*/id)arg4 ;
+(id)drawPath:(id)arg1 opaque:(char)arg2 scale:(float)arg3 padding:(IGPathPadding)arg4 style:(id)arg5 drawBlock:(/*^block*/id)arg6 ;
@end

