/*
* This header is generated by classdump-dyld 0.7
* on Monday, October 26, 2015 at 9:24:37 PM Central Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/21A1C6E8-DEFC-46E0-A287-C60E9807B6FE/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSDate, MPMusicPlayerController, NSString;

@interface IGAudioSession : NSObject {

	NSDate* _resignedActiveTime;
	MPMusicPlayerController* _musicPlayerController;
	NSString* _currentAudioCategory;
	char _overrideMuteSwitch;
	float _previousVolume;

}

@property (assign,nonatomic) char overrideMuteSwitch;              //@synthesize overrideMuteSwitch=_overrideMuteSwitch - In the implementation block
@property (assign,nonatomic) float previousVolume;                 //@synthesize previousVolume=_previousVolume - In the implementation block
+(id)sharedInstance;
-(void)setPreviousVolume:(float)arg1 ;
-(float)previousVolume;
-(char)overrideMuteSwitch;
-(void)setOverrideMuteSwitch:(char)arg1 ;
-(void)dealloc;
-(id)init;
-(void)volumeChanged:(id)arg1 ;
-(void)updateCategory;
-(void)audioSessionRouteChange:(id)arg1 ;
-(void)didBecomeActive;
-(void)willResignActive;
@end

