/*
* This header is generated by classdump-dyld 0.7
* on Tuesday, September 15, 2015 at 5:29:38 PM Central Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /var/mobile/Containers/Bundle/Application/78EC956B-7ED8-4B50-8025-C2B1976EEC28/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol IGAudioNUXControllerDelegate;
@class IGMediaOverlayIndicator;

@interface IGAudioNUXController : NSObject {

	char _hasShownPlaybackNUX;
	id<IGAudioNUXControllerDelegate> _delegate;
	IGMediaOverlayIndicator* _indicator;

}

@property (assign,nonatomic,__weak) id<IGAudioNUXControllerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,retain) IGMediaOverlayIndicator * indicator;                           //@synthesize indicator=_indicator - In the implementation block
@property (assign,nonatomic) char hasShownPlaybackNUX;                                      //@synthesize hasShownPlaybackNUX=_hasShownPlaybackNUX - In the implementation block
-(IGMediaOverlayIndicator *)indicator;
-(void)setIndicator:(IGMediaOverlayIndicator *)arg1 ;
-(void)didChangeMuteSwitch:(id)arg1 ;
-(void)didPressVolumeButton:(id)arg1 ;
-(void)showNUXForHardwareVolumeControl;
-(char)hasShownPlaybackNUX;
-(void)setHasShownPlaybackNUX:(char)arg1 ;
-(id)initWithIndicator:(id)arg1 ;
-(void)showOneTapIndicatorNUX;
-(void)didTapOnVideo;
-(void)dealloc;
-(void)setDelegate:(id<IGAudioNUXControllerDelegate>)arg1 ;
-(id<IGAudioNUXControllerDelegate>)delegate;
@end

