/*
* This header is generated by classdump-dyld 0.7
* on Tuesday, September 15, 2015 at 5:29:32 PM Central Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /var/mobile/Containers/Bundle/Application/78EC956B-7ED8-4B50-8025-C2B1976EEC28/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Instagram/IGAutocompleteAbstractStore.h>
#import <Instagram/IGAutocompleteAbstractStoreProtocol.h>

@class NSMutableDictionary, NSMutableArray, NSString;

@interface IGAutocompleteHashtagsStore : IGAutocompleteAbstractStore <IGAutocompleteAbstractStoreProtocol> {

	NSMutableDictionary* _hashtagExpirations;
	NSMutableArray* _allHashtags;
	NSMutableArray* _recentHashtags;

}

@property (nonatomic,retain) NSMutableArray * allHashtags;                 //@synthesize allHashtags=_allHashtags - In the implementation block
@property (nonatomic,retain) NSMutableArray * recentHashtags;              //@synthesize recentHashtags=_recentHashtags - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)sharedStore;
-(id)regexPattern;
-(id)hashtagsInString:(id)arg1 ;
-(void)addHashtag:(id)arg1 addToRecent:(char)arg2 ;
-(int)indexOfHashtag:(id)arg1 inArray:(id)arg2 ;
-(void)setExpiresForHashtag:(id)arg1 ;
-(void)removeExpiredHashtags;
-(void)addHashtagsFromText:(id)arg1 addToRecent:(char)arg2 ;
-(void)setExpiresForHashtags:(id)arg1 ;
-(NSMutableArray *)allHashtags;
-(void)setAllHashtags:(NSMutableArray *)arg1 ;
-(NSMutableArray *)recentHashtags;
-(void)setRecentHashtags:(NSMutableArray *)arg1 ;
-(id)init;
-(void)clear;
-(void)clearHistory;
-(void)archive;
@end

