/*
* This header is generated by classdump-dyld 1.0
* on Friday, May 13, 2016 at 9:28:46 PM Central Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/6C2D6691-0360-45BF-8623-49F0546803FE/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMutableDictionary, NSDictionary, NSMutableArray;

@interface IGBadgeHelper : NSObject {

	NSMutableDictionary* _badgeDict;
	NSMutableDictionary* _timestampDict;
	NSDictionary* _multipleAccountsBadgeDict;
	NSMutableArray* _updatedBadgeNames;

}
+(id)sharedBadgeHelper;
-(int)badgeCountForBadgeName:(id)arg1 ;
-(void)updateBadgeCount:(int)arg1 forBadgeName:(id)arg2 timestamp:(id)arg3 ;
-(void)fetchBadgesDict;
-(void)updateBadgeCount:(int)arg1 forBadgeName:(id)arg2 timestamp:(id)arg3 shouldHoldUpdates:(char)arg4 ;
-(void)performBadgeUpdates;
-(int)totalBadgeCount;
-(void)updateNeedsAttention;
-(void)broadcastUpdatedNeedsAttentionValue:(char)arg1 ;
-(char)shouldNeedAttention;
-(int)badgeCountForUserID:(id)arg1 ;
-(void)dealloc;
-(id)init;
@end

