/*
* This header is generated by classdump-dyld 0.7
* on Thursday, August 27, 2015 at 8:51:37 PM Central Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /var/mobile/Containers/Bundle/Application/2DC1EEC6-8BB6-4C9F-8658-A819865606D1/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Instagram/Instagram-Structs.h>
#import <Instagram/IGImageFilter.h>

@class IGSurface;

@interface IGBilateralFilter : IGImageFilter {

	char _needsConfigure;
	GLKVector2 _blurVector;
	IGSurface* _intermediateTexture;
	float _rangeSigma;
	float _spatialSigma;
	unsigned _spatialKernelSize;

}

@property (assign,nonatomic) float rangeSigma;                          //@synthesize rangeSigma=_rangeSigma - In the implementation block
@property (assign,nonatomic) float spatialSigma;                        //@synthesize spatialSigma=_spatialSigma - In the implementation block
@property (nonatomic,readonly) unsigned spatialKernelSize;              //@synthesize spatialKernelSize=_spatialKernelSize - In the implementation block
-(void)render:(id)arg1 to:(id)arg2 program:(id)arg3 ;
-(id)fragmentShaderPrecision;
-(id)fragmentFunctions;
-(void)configureProgram:(id)arg1 ;
-(float)rangeSigma;
-(void)setRangeSigma:(float)arg1 ;
-(float)spatialSigma;
-(void)setSpatialSigma:(float)arg1 ;
-(unsigned)spatialKernelSize;
-(id)initWithKernelSize:(unsigned)arg1 ;
-(id)fragmentShader;
-(id)init;
-(id)copyWithZone:(NSZone*)arg1 ;
@end

