/*
* This header is generated by classdump-dyld 1.0
* on Monday, February 29, 2016 at 3:36:47 PM Central Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/8E0CB1D4-3D23-4350-ABAD-ADD1AC46A9D0/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Instagram/Instagram-Structs.h>
#import <UIKit/UITableViewCell.h>
#import <UIKit/UITextFieldDelegate.h>

@protocol IGBusinessConversionEditableProfileCellDelegate;
@class IGTextField, NSString, NSNumber, UILabel, UIImageView;

@interface IGBusinessConversionEditableProfileCell : UITableViewCell <UITextFieldDelegate> {

	char _shouldShowDisclosure;
	IGTextField* _textField;
	NSString* _headerText;
	NSNumber* _dataKey;
	id<IGBusinessConversionEditableProfileCellDelegate> _delegate;
	UILabel* _headerLabel;
	UIImageView* _disclosureIndicator;

}

@property (nonatomic,retain) IGTextField * textField;                                                          //@synthesize textField=_textField - In the implementation block
@property (nonatomic,copy) NSString * headerText;                                                              //@synthesize headerText=_headerText - In the implementation block
@property (nonatomic,retain) NSNumber * dataKey;                                                               //@synthesize dataKey=_dataKey - In the implementation block
@property (assign,nonatomic) char shouldShowDisclosure;                                                        //@synthesize shouldShowDisclosure=_shouldShowDisclosure - In the implementation block
@property (assign,nonatomic,__weak) id<IGBusinessConversionEditableProfileCellDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,retain) UILabel * headerLabel;                                                            //@synthesize headerLabel=_headerLabel - In the implementation block
@property (nonatomic,retain) UIImageView * disclosureIndicator;                                                //@synthesize disclosureIndicator=_disclosureIndicator - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(UIImageView *)disclosureIndicator;
-(void)setDisclosureIndicator:(UIImageView *)arg1 ;
-(void)setShouldShowDisclosure:(char)arg1 ;
-(void)setDelegate:(id<IGBusinessConversionEditableProfileCellDelegate>)arg1 ;
-(void)layoutSubviews;
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2 ;
-(id<IGBusinessConversionEditableProfileCellDelegate>)delegate;
-(void)textFieldDidBeginEditing:(id)arg1 ;
-(char)textField:(id)arg1 shouldChangeCharactersInRange:(NSRange)arg2 replacementString:(id)arg3 ;
-(char)textFieldShouldClear:(id)arg1 ;
-(char)textFieldShouldReturn:(id)arg1 ;
-(IGTextField *)textField;
-(void)setHeaderLabel:(UILabel *)arg1 ;
-(UILabel *)headerLabel;
-(void)setTextField:(IGTextField *)arg1 ;
-(char)shouldShowDisclosure;
-(NSString *)headerText;
-(void)setHeaderText:(NSString *)arg1 ;
-(void)setDataKey:(NSNumber *)arg1 ;
-(NSNumber *)dataKey;
@end

