/*
* This header is generated by classdump-dyld 1.0
* on Monday, February 29, 2016 at 3:36:47 PM Central Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/8E0CB1D4-3D23-4350-ABAD-ADD1AC46A9D0/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Instagram/Instagram-Structs.h>
#import <Instagram/IGViewController.h>
#import <Instagram/IGBusinessConversionFlowStep.h>

@protocol IGBusinessConversionViewControllerDelegate;
@class UILabel, UIButton, IGButton, UIImageView, NSString;

@interface IGBusinessConversionViewController : IGViewController <IGBusinessConversionFlowStep> {

	id<IGBusinessConversionViewControllerDelegate> _delegate;
	UILabel* _titleLabel;
	UILabel* _subtitleLabel;
	UIButton* _dismissButton;
	IGButton* _continueButton;
	UIImageView* _businessIconImageView;
	UILabel* _disclaimerLabel;

}

@property (assign,nonatomic,__weak) id<IGBusinessConversionViewControllerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,retain) UILabel * titleLabel;                                                        //@synthesize titleLabel=_titleLabel - In the implementation block
@property (nonatomic,retain) UILabel * subtitleLabel;                                                     //@synthesize subtitleLabel=_subtitleLabel - In the implementation block
@property (nonatomic,retain) UIButton * dismissButton;                                                    //@synthesize dismissButton=_dismissButton - In the implementation block
@property (nonatomic,retain) IGButton * continueButton;                                                   //@synthesize continueButton=_continueButton - In the implementation block
@property (nonatomic,retain) UIImageView * businessIconImageView;                                         //@synthesize businessIconImageView=_businessIconImageView - In the implementation block
@property (nonatomic,retain) UILabel * disclaimerLabel;                                                   //@synthesize disclaimerLabel=_disclaimerLabel - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(IGButton *)continueButton;
-(void)setContinueButton:(IGButton *)arg1 ;
-(id)analyticsInfoForFlowStep;
-(void)setBusinessIconImageView:(UIImageView *)arg1 ;
-(UIImageView *)businessIconImageView;
-(void)setDisclaimerLabel:(UILabel *)arg1 ;
-(UILabel *)disclaimerLabel;
-(id)initializeContinueButtonWithFrame:(CGRect)arg1 ;
-(void)openPageSelectionViewControllerWithAccessToken:(id)arg1 ;
-(void)openPageSelectionViewControllerWithCurrentUserAccessToken;
-(void)getAccessTokenAndPushBusinessSelectorIfPossible;
-(void)setDelegate:(id<IGBusinessConversionViewControllerDelegate>)arg1 ;
-(id<IGBusinessConversionViewControllerDelegate>)delegate;
-(char)prefersStatusBarHidden;
-(void)viewWillLayoutSubviews;
-(UILabel *)titleLabel;
-(UILabel *)subtitleLabel;
-(void)viewDidLoad;
-(void)dismiss;
-(void)setTitleLabel:(UILabel *)arg1 ;
-(void)setSubtitleLabel:(UILabel *)arg1 ;
-(UIButton *)dismissButton;
-(void)setDismissButton:(UIButton *)arg1 ;
-(char)prefersNavigationBarHidden;
@end

