/*
* This header is generated by classdump-dyld 0.7
* on Tuesday, October 13, 2015 at 10:19:52 PM Central Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /var/mobile/Containers/Bundle/Application/095E6AAC-0201-41F1-901D-3BA0DA7A9B94/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Instagram/Instagram-Structs.h>
#import <UIKit/UIView.h>

@class UIImageView, NSMutableArray;

@interface IGCameraBar : UIView {

	UIImageView* _backgroundImageView;
	NSMutableArray* _barViews;

}

@property (nonatomic,retain) UIImageView * backgroundImageView;              //@synthesize backgroundImageView=_backgroundImageView - In the implementation block
@property (nonatomic,readonly) NSMutableArray * barViews;                    //@synthesize barViews=_barViews - In the implementation block
-(void)setIsTranslucent:(char)arg1 ;
-(void)pushView:(id)arg1 animated:(char)arg2 ;
-(void)popViewAnimated:(char)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(UIImageView *)backgroundImageView;
-(NSMutableArray *)barViews;
-(void)setBackgroundImageView:(UIImageView *)arg1 ;
@end

