/*
* This header is generated by classdump-dyld 0.7
* on Tuesday, February 2, 2016 at 7:26:11 PM Central Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3AACC7FB-0FE9-4871-925D-3A035BF7F4E1/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Instagram/Instagram-Structs.h>
#import <Instagram/IGCameraBar.h>

@class CALayer, NSMutableArray;

@interface IGCameraNavigationBar : IGCameraBar {

	char _shouldIgnoreHitsInView;
	CALayer* _bottomBorder;
	NSMutableArray* _navigationItems;

}

@property (nonatomic,retain) CALayer * bottomBorder;                        //@synthesize bottomBorder=_bottomBorder - In the implementation block
@property (assign,nonatomic) char shouldIgnoreHitsInView;                   //@synthesize shouldIgnoreHitsInView=_shouldIgnoreHitsInView - In the implementation block
@property (nonatomic,retain) NSMutableArray * navigationItems;              //@synthesize navigationItems=_navigationItems - In the implementation block
+(int)toolbarButtonPadding;
-(id)viewForNavigationItem:(id)arg1 ;
-(char)shouldIgnoreHitsInView;
-(void)reloadNavigationItem:(id)arg1 animated:(char)arg2 ;
-(void)setShouldIgnoreHitsInView:(char)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(id)hitTest:(CGPoint)arg1 withEvent:(id)arg2 ;
-(NSMutableArray *)navigationItems;
-(void)popNavigationItemAnimated:(char)arg1 ;
-(void)pushNavigationItem:(id)arg1 animated:(char)arg2 ;
-(void)setNavigationItems:(NSMutableArray *)arg1 ;
-(CALayer *)bottomBorder;
-(void)setBottomBorder:(CALayer *)arg1 ;
@end

