/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, February 16, 2016 at 3:16:02 PM Central Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/C13E072C-E6C1-44DA-8A86-89C97396B2E7/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Instagram/Instagram-Structs.h>
#import <UIKit/UIView.h>

@class CADisplayLink, UIColor;

@interface IGCameraFocusIndicator : UIView {

	CADisplayLink* _reviewDisplayLink;
	int _frame;
	int _stopIn;
	UIColor* _indicatorColor;

}

@property (nonatomic,retain) UIColor * indicatorColor;              //@synthesize indicatorColor=_indicatorColor - In the implementation block
-(void)startAnimatingAtPoint:(CGPoint)arg1 ;
-(void)completeAnimation;
-(void)stopRenderLoop;
-(void)startRenderLoop;
-(UIColor *)indicatorColor;
-(void)setIndicatorColor:(UIColor *)arg1 ;
-(void)drawRect:(CGRect)arg1 ;
-(void)dealloc;
-(id)init;
-(void)stopAnimating;
@end

