/*
* This header is generated by classdump-dyld 0.7
* on Tuesday, October 6, 2015 at 9:46:07 PM Central Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /var/mobile/Containers/Bundle/Application/E660306A-8A68-4027-9100-A800454451FF/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Instagram/IGUserCell.h>

@class UIView;

@interface IGClusterBrowsingUserCell : IGUserCell {

	UIView* _bottomLineSeparator;

}

@property (nonatomic,retain) UIView * bottomLineSeparator;              //@synthesize bottomLineSeparator=_bottomLineSeparator - In the implementation block
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2 analyticsDelegate:(id)arg3 ;
-(void)setBottomLineSeparator:(UIView *)arg1 ;
-(UIView *)bottomLineSeparator;
-(void)layoutSubviews;
@end

