/*
* This header is generated by classdump-dyld 0.7
* on Tuesday, September 15, 2015 at 5:29:35 PM Central Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /var/mobile/Containers/Bundle/Application/78EC956B-7ED8-4B50-8025-C2B1976EEC28/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Instagram/Instagram-Structs.h>
#import <UIKit/UIView.h>

@protocol IGCommentActionViewDelegate;
@class UIButton;

@interface IGCommentActionView : UIView {

	int _deleteButtonType;
	id<IGCommentActionViewDelegate> _delegate;
	UIButton* _replyButton;
	UIButton* _deleteButton;

}

@property (assign,nonatomic) int deleteButtonType;                                         //@synthesize deleteButtonType=_deleteButtonType - In the implementation block
@property (assign,nonatomic,__weak) id<IGCommentActionViewDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,readonly) float maxWidth; 
@property (nonatomic,retain) UIButton * replyButton;                                       //@synthesize replyButton=_replyButton - In the implementation block
@property (nonatomic,retain) UIButton * deleteButton;                                      //@synthesize deleteButton=_deleteButton - In the implementation block
-(UIButton *)replyButton;
-(void)replyButtonTapped:(id)arg1 ;
-(void)setDeleteButtonType:(int)arg1 ;
-(int)deleteButtonType;
-(void)setReplyButton:(UIButton *)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)setDelegate:(id<IGCommentActionViewDelegate>)arg1 ;
-(id<IGCommentActionViewDelegate>)delegate;
-(void)deleteButtonTapped:(id)arg1 ;
-(UIButton *)deleteButton;
-(void)setDeleteButton:(UIButton *)arg1 ;
-(float)maxWidth;
@end

