/*
* This header is generated by classdump-dyld 1.0
* on Monday, April 11, 2016 at 7:41:46 PM Central Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /private/var/mobile/Containers/Bundle/Application/F2F7650E-6416-4D13-A52F-83DEE7C62D71/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSArray;

@interface IGCollectionViewChangeSet : NSObject {

	NSArray* _addedIndexPaths;
	NSArray* _removedIndexPaths;
	NSArray* _fromMoveIndexPaths;
	NSArray* _toMoveIndexPaths;

}

@property (nonatomic,retain) NSArray * addedIndexPaths;                 //@synthesize addedIndexPaths=_addedIndexPaths - In the implementation block
@property (nonatomic,retain) NSArray * removedIndexPaths;               //@synthesize removedIndexPaths=_removedIndexPaths - In the implementation block
@property (nonatomic,retain) NSArray * fromMoveIndexPaths;              //@synthesize fromMoveIndexPaths=_fromMoveIndexPaths - In the implementation block
@property (nonatomic,retain) NSArray * toMoveIndexPaths;                //@synthesize toMoveIndexPaths=_toMoveIndexPaths - In the implementation block
-(NSArray *)removedIndexPaths;
-(void)setRemovedIndexPaths:(NSArray *)arg1 ;
-(void)setAddedIndexPaths:(NSArray *)arg1 ;
-(void)setFromMoveIndexPaths:(NSArray *)arg1 ;
-(void)setToMoveIndexPaths:(NSArray *)arg1 ;
-(NSArray *)addedIndexPaths;
-(NSArray *)fromMoveIndexPaths;
-(NSArray *)toMoveIndexPaths;
-(id)description;
@end

