

@interface IGColors : NSObject
+(id)linkHighlightedColor;
+(id)emphasizedActionColor;
+(id)searchButtonBackgroundColor;
+(id)navigationBarOverlayColor;
+(id)tabBarIconSelectedColor;
+(id)tabBarBackgroundColor;
+(id)creationBackgroundColor;
+(id)creationFilterTrayBackgroundColor;
+(id)creationPhotoTrayBackgroundColor;
+(id)creationToolContainerBackgroundColor;
+(id)creationFilterControlTextColor;
+(id)creationTextColor;
+(id)creationNavigationBarBackgroundColor;
+(id)creationAccentColor;
+(id)destructiveColor;
+(id)boldLinkColor;
+(id)boldLinkHighlightedColor;
+(id)veryLightTextColor;
+(id)accessoryColor;
+(id)lightBarBackgroundColor;
+(id)errorColor;
+(id)darkButtonColor;
+(id)heartColor;
+(id)ufiActionIconColor;
+(id)selectedAccessoryColor;
+(id)systemDestructiveColor;
+(id)tabBarCameraIconColor;
+(id)tabBarCameraBackgroundColor;
+(id)tabBarCameraBackgroundHighlightedColor;
+(id)tabBarItemBackgroundSelectedColor;
+(id)tabBarIconColor;
+(id)tabBarItemBackgroundColor;
+(id)navigationBarBackgroundColor;
+(id)activeSearchNavigationBarBackgroundColor;
+(id)validAccessoryColor;
+(id)searchButtonTextColor;
+(id)searchButtonHighlightedBackgroundColor;
+(id)searchEditingBackgroundColor;
+(id)lightCreationBackgroundColor;
+(id)creationTintColor;
+(id)creationTabIconColor;
+(id)businessConversionBackgroundColor;
+(id)linkColor;
+(id)systemBlueColor;
+(id)separatorColor;
+(id)textColor;
+(id)badgeColor;
+(id)secondaryTextColor;
+(id)navigationBarTintColor;
@end

