/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, February 16, 2016 at 3:16:01 PM Central Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/C13E072C-E6C1-44DA-8A86-89C97396B2E7/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class UIImage, NSNumber;

@interface IGDecodedImageCacheObject : NSObject {

	UIImage* _image;
	NSNumber* _dataLength;

}

@property (nonatomic,retain) UIImage * image;                    //@synthesize image=_image - In the implementation block
@property (nonatomic,retain) NSNumber * dataLength;              //@synthesize dataLength=_dataLength - In the implementation block
-(void)setImage:(UIImage *)arg1 ;
-(UIImage *)image;
-(NSNumber *)dataLength;
-(void)setDataLength:(NSNumber *)arg1 ;
@end

