/*
* This header is generated by classdump-dyld 0.7
* on Monday, October 26, 2015 at 9:24:37 PM Central Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/21A1C6E8-DEFC-46E0-A287-C60E9807B6FE/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class IGMotionManager, NSOperationQueue;

@interface IGDeviceOrientation : NSObject {

	int _orientationObservers;
	int _pauseCount;
	IGMotionManager* _motionManager;
	NSOperationQueue* _queue;
	int _orientation;

}

@property (nonatomic,readonly) int orientation;                                                                                             //@synthesize orientation=_orientation - In the implementation block
@property (getter=isGeneratingDeviceOrientationNotifications,nonatomic,readonly) char generatesDeviceOrientationNotifications; 
+(id)currentDevice;
-(void)pauseGeneratingDeviceOrientationNotifications;
-(void)resumeGeneratingDeviceOrientationNotifications;
-(void)dealloc;
-(id)init;
-(char)isGeneratingDeviceOrientationNotifications;
-(int)orientation;
-(void)reset;
-(void)beginGeneratingDeviceOrientationNotifications;
-(void)endGeneratingDeviceOrientationNotifications;
-(void)startMotionUpdates;
-(void)stopMotionUpdates;
@end

