/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 13, 2015 at 8:04:07 PM Central Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/80FB49E7-07A3-4438-9519-37CDCDE82DE6/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface IGDirectoryCleaner : NSObject
+(char)trashItemAtPath:(id)arg1 error:(id*)arg2 ;
+(void)startBackgroundTrashCleanupTask;
+(id)trashPath;
+(void)performFolderCleanup:(id)arg1 removeRootFolder:(char)arg2 ;
+(id)trashPathForPath:(id)arg1 ;
@end

