/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 13, 2015 at 8:03:49 PM Central Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/80FB49E7-07A3-4438-9519-37CDCDE82DE6/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Instagram/Instagram-Structs.h>
#import <UIKit/UIView.h>

@class NSArray;

@interface IGDirectInboxActionView : UIView {

	NSArray* _inboxActionButtons;

}

@property (nonatomic,retain) NSArray * inboxActionButtons;              //@synthesize inboxActionButtons=_inboxActionButtons - In the implementation block
-(NSArray *)inboxActionButtons;
-(void)setInboxActionButtons:(NSArray *)arg1 ;
-(void)setInboxActions:(id)arg1 ;
-(float)fullyExtendedWidth;
-(void)setFrame:(CGRect)arg1 ;
@end

