/*
* This header is generated by classdump-dyld 1.0
* on Monday, April 11, 2016 at 7:41:39 PM Central Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /private/var/mobile/Containers/Bundle/Application/F2F7650E-6416-4D13-A52F-83DEE7C62D71/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Instagram/IGViewController.h>
#import <Instagram/IGDirectInboxControllerType.h>
#import <Instagram/IGDirectThreadViewControllerDelegate.h>
#import <Instagram/IGUIPerfLoggable.h>

@class NSString;

@interface IGDirectMainInboxViewController2 : IGViewController <IGDirectInboxControllerType, IGDirectThreadViewControllerDelegate, IGUIPerfLoggable>

@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(char)shouldLogEvent:(unsigned)arg1 ;
-(unsigned)lastLogEvent;
-(void)allEventsLoggedWithResult:(id)arg1 ;
-(void)refreshDataWithClearCount:(char)arg1 ;
-(void)pushToThreadWithThreadId:(id)arg1 animated:(char)arg2 logResult:(id)arg3 ;
-(unsigned)inboxSubscriptionStatus;
-(void)threadViewController:(id)arg1 didUpdateFromThread:(id)arg2 toThread:(id)arg3 ;
-(void)scrollToTopAnimated:(char)arg1 ;
-(void)viewDidLoad;
@end

