/*
* This header is generated by classdump-dyld 1.0
* on Friday, May 13, 2016 at 9:28:35 PM Central Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/6C2D6691-0360-45BF-8623-49F0546803FE/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/NSCoding.h>

@protocol NSCoding;
@interface IGDiskCacheObject : NSObject <NSCoding> {

	unsigned _cost;
	id<NSCoding> _object;

}

@property (assign,nonatomic) unsigned cost;                    //@synthesize cost=_cost - In the implementation block
@property (nonatomic,retain) id<NSCoding> object;              //@synthesize object=_object - In the implementation block
-(id)initWithObject:(id)arg1 cost:(unsigned)arg2 ;
-(void)setCost:(unsigned)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(id<NSCoding>)object;
-(void)setObject:(id<NSCoding>)arg1 ;
-(unsigned)cost;
@end

