/*
* This header is generated by classdump-dyld 0.7
* on Tuesday, January 19, 2016 at 3:14:50 PM Central Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/4DC55608-3697-420B-B226-BE8BA2A1BD0A/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UICollectionViewLayoutInvalidationContext.h>

@interface IGDirectThreadLayoutInvalidationContext : UICollectionViewLayoutInvalidationContext {

	char _igInvalidateCollectionViewContentSize;
	char _igInvalidateAttributes;
	char _igInvalidateEverything;

}

@property (assign,nonatomic) char igInvalidateCollectionViewContentSize;              //@synthesize igInvalidateCollectionViewContentSize=_igInvalidateCollectionViewContentSize - In the implementation block
@property (assign,nonatomic) char igInvalidateAttributes;                             //@synthesize igInvalidateAttributes=_igInvalidateAttributes - In the implementation block
@property (assign,nonatomic) char igInvalidateEverything;                             //@synthesize igInvalidateEverything=_igInvalidateEverything - In the implementation block
-(void)setIgInvalidateEverything:(char)arg1 ;
-(void)mergeWithInvalidationContext:(id)arg1 ;
-(char)igInvalidateAttributes;
-(char)igInvalidateCollectionViewContentSize;
-(char)igInvalidateEverything;
-(void)setIgInvalidateCollectionViewContentSize:(char)arg1 ;
-(void)setIgInvalidateAttributes:(char)arg1 ;
-(id)description;
@end

