/*
* This header is generated by classdump-dyld 0.7
* on Tuesday, September 15, 2015 at 5:29:41 PM Central Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /var/mobile/Containers/Bundle/Application/78EC956B-7ED8-4B50-8025-C2B1976EEC28/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Instagram/NSCoding.h>

@class IGUser;

@interface IGDirectedPostRecipient : NSObject <NSCoding> {

	char _hasRead;
	char _hasLiked;
	char _hasCommented;
	IGUser* _user;

}

@property (readonly) IGUser * user;                //@synthesize user=_user - In the implementation block
@property (assign) char hasRead;                   //@synthesize hasRead=_hasRead - In the implementation block
@property (assign) char hasLiked;                  //@synthesize hasLiked=_hasLiked - In the implementation block
@property (assign) char hasCommented;              //@synthesize hasCommented=_hasCommented - In the implementation block
-(char)hasLiked;
-(void)setHasCommented:(char)arg1 ;
-(char)hasCommented;
-(void)updateProperty:(id)arg1 withValue:(id)arg2 ;
-(void)setHasLiked:(char)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(id)description;
-(id)initWithDictionary:(id)arg1 ;
-(IGUser *)user;
-(char)hasRead;
-(void)setHasRead:(char)arg1 ;
@end

