/*
* This header is generated by classdump-dyld 0.7
* on Tuesday, October 13, 2015 at 10:19:55 PM Central Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /var/mobile/Containers/Bundle/Application/095E6AAC-0201-41F1-901D-3BA0DA7A9B94/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Instagram/Instagram-Structs.h>
#import <Instagram/IGDirectContentExpandableCell.h>
#import <Instagram/IGDirectVideoViewDelegate.h>

@class IGDirectVideoView, NSString;

@interface IGDirectVideoExpandableCell : IGDirectContentExpandableCell <IGDirectVideoViewDelegate> {

	IGDirectVideoView* _videoView;

}

@property (nonatomic,retain) IGDirectVideoView * videoView;              //@synthesize videoView=_videoView - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)completeAnimation;
-(CGSize)photoSizeForWidth:(float)arg1 ;
-(CGSize)photoSizeForHeight:(float)arg1 ;
-(void)stopAnimated:(char)arg1 ;
-(void)videoView:(id)arg1 didFailToPlayWithError:(id)arg2 ;
-(void)play;
-(void)setVideoView:(IGDirectVideoView *)arg1 ;
-(IGDirectVideoView *)videoView;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(void)layoutSubviews;
-(void)stop;
-(void)prepareForReuse;
-(void)setContent:(id)arg1 ;
-(void)beginAnimation;
@end

