/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 13, 2015 at 8:03:52 PM Central Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/80FB49E7-07A3-4438-9519-37CDCDE82DE6/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSString, IGFileCoordinator;

@interface IGEventFeedDataArchiver : NSObject {

	NSString* _eventId;
	IGFileCoordinator* _fileCoordinator;

}

@property (nonatomic,copy,readonly) NSString * eventId;                        //@synthesize eventId=_eventId - In the implementation block
@property (nonatomic,retain) IGFileCoordinator * fileCoordinator;              //@synthesize fileCoordinator=_fileCoordinator - In the implementation block
-(IGFileCoordinator *)fileCoordinator;
-(id)initWithEventId:(id)arg1 ;
-(char)archiveEventFeedData:(id)arg1 ;
-(id)unarchiveEventFeedData;
-(void)setFileCoordinator:(IGFileCoordinator *)arg1 ;
-(NSString *)eventId;
@end

