/*
* This header is generated by classdump-dyld 0.7
* on Tuesday, February 2, 2016 at 7:26:17 PM Central Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3AACC7FB-0FE9-4871-925D-3A035BF7F4E1/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface IGExploreRaindropLoggingHelper : NSObject
+(void)logMediaClick:(id)arg1 sectionType:(int)arg2 section:(int)arg3 mediaIndex:(int)arg4 numberOfItemsPerRow:(int)arg5 clusterKey:(id)arg6 navState:(id)arg7 ;
+(void)logPhotoImpression:(id)arg1 sectionType:(int)arg2 viewed:(char)arg3 subImpression:(char)arg4 section:(int)arg5 mediaIndex:(int)arg6 numberOfItemsPerRow:(int)arg7 clusterKey:(id)arg8 navState:(id)arg9 ;
+(id)clickPointForMedia:(id)arg1 ;
@end

