/*
* This header is generated by classdump-dyld 0.7
* on Monday, October 26, 2015 at 9:24:42 PM Central Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/21A1C6E8-DEFC-46E0-A287-C60E9807B6FE/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UIView.h>

@protocol IGExploreComposedPeopleYouFollowViewDelegate;
@class UILabel, NSArray;

@interface IGExploreComposedPeopleYouFollowView : UIView {

	id<IGExploreComposedPeopleYouFollowViewDelegate> _delegate;
	UILabel* _titleLabel;
	NSArray* _peopleViews;
	NSArray* _separatorViews;

}

@property (assign,nonatomic,__weak) id<IGExploreComposedPeopleYouFollowViewDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic,__weak) UILabel * titleLabel;                                                   //@synthesize titleLabel=_titleLabel - In the implementation block
@property (nonatomic,readonly) NSArray * peopleViews;                                                       //@synthesize peopleViews=_peopleViews - In the implementation block
@property (nonatomic,readonly) NSArray * separatorViews;                                                    //@synthesize separatorViews=_separatorViews - In the implementation block
-(void)addAndConfigureAllSubviews;
-(void)didTapPeopleView:(id)arg1 ;
-(void)configureSubviewsLayout;
-(NSArray *)peopleViews;
-(id)initWithFrameWidth:(float)arg1 peopleViews:(id)arg2 ;
-(NSArray *)separatorViews;
-(void)setDelegate:(id<IGExploreComposedPeopleYouFollowViewDelegate>)arg1 ;
-(void)layoutSubviews;
-(id<IGExploreComposedPeopleYouFollowViewDelegate>)delegate;
-(UILabel *)titleLabel;
-(void)setTitleLabel:(UILabel *)arg1 ;
@end

