/*
* This header is generated by classdump-dyld 0.7
* on Tuesday, September 15, 2015 at 5:29:42 PM Central Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /var/mobile/Containers/Bundle/Application/78EC956B-7ED8-4B50-8025-C2B1976EEC28/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Instagram/IGServiceHelperProtocol.h>

@class NSString;

@interface IGFacebookHelper : NSObject <IGServiceHelperProtocol> {

	char _isAskingForAdditionalPermisons;
	char _isRestoringSession;
	char _isMigratingSession;

}

@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)sharedIGFacebookHelper;
-(id)currentUserInfo;
-(id)sharingInfo;
-(char)canShare;
-(void)shareFeedItem:(id)arg1 fromViewController:(id)arg2 ;
-(void)loginWithBasicPermissions;
-(void)logoutAndUnlink;
-(char)isConfigurable;
-(char)hasAdvancedOptions;
-(char)requiresLocationCoordinate;
-(char)isAvailableInCurrentLocale;
-(char)supportsMediaType:(int)arg1 ;
-(id)shortServiceName;
-(void)loginWithStandardPermissions;
-(char)needsToReauthorize;
-(void)reauthorizeIfNeeded;
-(id)viewControllerForAdvancedOptions;
-(char)takeIsAskingForAdditionalPermissions;
-(void)restoreSessionForPk:(id)arg1 ;
-(id)pageName;
-(void)onLoginSuccessful;
-(void)fbDidLogin;
-(void)fbDidExtendToken:(id)arg1 expiresAt:(id)arg2 ;
-(void)fbDidNotLogin;
-(void)loginWithPermissions:(id)arg1 ;
-(id)urlSchemeSuffix;
-(void)sessionStateChanged:(id)arg1 state:(int)arg2 error:(id)arg3 ;
-(id)loadSessionWithUserPk:(id)arg1 ;
-(void)migrateSession:(id)arg1 toUserPk:(id)arg2 ;
-(void)fetchUserInfoWithFetchStrategy:(int)arg1 completionBlock:(/*^block*/id)arg2 ;
-(void)sendCredentialsToServer;
-(void)notifyAuthCompleted;
-(char)hasAuthorizedWallPost;
-(void)fbSessionInvalidated;
-(void)fbDidLogout;
-(void)setIsAskingForAdditionalPermissions:(char)arg1 ;
-(char)hasAuthorizedManagePages;
-(void)setPageName:(id)arg1 ;
-(void)showHUDWithText:(id)arg1 ;
-(void)hideHUD;
-(char)isConfigured;
-(void)dealloc;
-(id)init;
-(id)serviceName;
-(void)logout;
-(void)setPageAccessToken:(id)arg1 ;
-(id)pageAccessToken;
@end

