/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, February 16, 2016 at 3:15:33 PM Central Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/C13E072C-E6C1-44DA-8A86-89C97396B2E7/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <Instagram/Instagram-Structs.h>
@interface IGFeedItemTextCellFactory : NSObject
+(void)registerCellWithCollectionView:(id)arg1 ;
+(id)textCellFromCollectionView:(id)arg1 indexPath:(id)arg2 ;
+(void)configureCell:(id)arg1 atRow:(int)arg2 feedItem:(id)arg3 configuration:(id)arg4 attributes:(id)arg5 containerWidth:(float)arg6 cellDelegate:(id)arg7 loggingDelegate:(id)arg8 ;
+(float)textWidthContainedInWidth:(float)arg1 ;
+(id)styledStringForFeedItem:(id)arg1 attributes:(id)arg2 configuration:(id)arg3 commentIndex:(int)arg4 width:(float)arg5 ;
+(float)textBottomPadding;
+(CGSize)textCellSizeWithAttributes:(id)arg1 configuration:(id)arg2 feedItem:(id)arg3 row:(int)arg4 containerWidth:(float)arg5 ;
@end

