/*
* This header is generated by classdump-dyld 0.7
* on Tuesday, October 6, 2015 at 9:46:06 PM Central Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /var/mobile/Containers/Bundle/Application/E660306A-8A68-4027-9100-A800454451FF/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface IGFeedItemViewingSession : NSObject {

	char _hasSeenMediaTopLeftPoint;
	char _hasSeenMediaBottomRightPoint;

}

@property (assign,nonatomic) char hasSeenMediaTopLeftPoint;                  //@synthesize hasSeenMediaTopLeftPoint=_hasSeenMediaTopLeftPoint - In the implementation block
@property (assign,nonatomic) char hasSeenMediaBottomRightPoint;              //@synthesize hasSeenMediaBottomRightPoint=_hasSeenMediaBottomRightPoint - In the implementation block
-(char)hasSeenMediaTopLeftPoint;
-(void)setHasSeenMediaTopLeftPoint:(char)arg1 ;
-(char)hasSeenMediaBottomRightPoint;
-(void)setHasSeenMediaBottomRightPoint:(char)arg1 ;
@end

