/*
* This header is generated by classdump-dyld 0.7
* on Tuesday, January 19, 2016 at 3:14:52 PM Central Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/4DC55608-3697-420B-B226-BE8BA2A1BD0A/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Instagram/IGFeedConfigurationType.h>

@class IGFeedDefaultConfiguration, NSString;

@interface IGFeedSingleFeedConfiguration : NSObject <IGFeedConfigurationType> {

	char _showFollowButton;
	char _showAttribution;
	IGFeedDefaultConfiguration* _defaultConfig;

}

@property (assign,nonatomic) char showFollowButton;                                     //@synthesize showFollowButton=_showFollowButton - In the implementation block
@property (assign,nonatomic) char showAttribution;                                      //@synthesize showAttribution=_showAttribution - In the implementation block
@property (nonatomic,readonly) IGFeedDefaultConfiguration * defaultConfig;              //@synthesize defaultConfig=_defaultConfig - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(char)enablePivotGridAfterCommentForFeedItem:(id)arg1 ;
-(char)shouldHideFeedItem:(id)arg1 ;
-(int)hiddenCellTypeForFeedItem:(id)arg1 ;
-(char)enablePivoForFeedItem:(id)arg1 ;
-(char)allowSponsoredContextForFeedItem:(id)arg1 ;
-(char)showExploreContextForFeedItem:(id)arg1 ;
-(char)showFollowButtonForFeedItem:(id)arg1 ;
-(char)shouldCollapseCaptionForFeedItem:(id)arg1 ;
-(char)showFollowButton;
-(void)setShowFollowButton:(char)arg1 ;
-(void)setShowAttribution:(char)arg1 ;
-(char)showAttribution;
-(id)init;
-(IGFeedDefaultConfiguration *)defaultConfig;
@end

