/*
* This header is generated by classdump-dyld 0.7
* on Tuesday, October 13, 2015 at 10:19:58 PM Central Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /var/mobile/Containers/Bundle/Application/095E6AAC-0201-41F1-901D-3BA0DA7A9B94/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol IGFeedStatusViewDynamicHeightProtocol <NSObject>
@optional
-(float)visibleContentHeight;

@required
-(void)feedStatusView:(id)arg1 wantsChangeToHeight:(float)arg2;

@end

