/*
* This header is generated by classdump-dyld 1.0
* on Monday, February 29, 2016 at 3:36:42 PM Central Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/8E0CB1D4-3D23-4350-ABAD-ADD1AC46A9D0/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface IGFeedItemInvalidationHelper : NSObject
+(int)adHideFlowVersionForFeedItem:(id)arg1 ;
+(char)isFeedItemWaitingForExpansionAfterHide:(id)arg1 ;
+(void)hideFeedItem:(id)arg1 forReason:(id)arg2 withExtraDictionary:(id)arg3 ;
+(char)isFeedItemInvalid:(id)arg1 ;
+(char)shouldFeedItemDisplay:(id)arg1 ;
+(char)hasSelectedReasonForInvalidFeedItem:(id)arg1 ;
+(id)dictionaryForHiddenAds;
+(id)reasonForInvalidFeedItem:(id)arg1 ;
+(id)reasonForUserHidingFeedItem:(id)arg1 ;
+(char)isAlreadyInstalledAppAds:(id)arg1 ;
+(void)postHideReasonSelectedNotificationForFeedItem:(id)arg1 forReason:(id)arg2 withExtraDictionary:(id)arg3 ;
+(char)isFeedItemWaitingForHideReason:(id)arg1 ;
+(void)markFeedItemAsNotVisibleIfInvalid:(id)arg1 ;
@end

