/*
* This header is generated by classdump-dyld 0.7
* on Tuesday, January 19, 2016 at 3:14:52 PM Central Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/4DC55608-3697-420B-B226-BE8BA2A1BD0A/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class IGHeartView, UICollectionView;

@interface IGFeedHeartAnimator : NSObject {

	char _usesLegacyAnimation;
	IGHeartView* _heartImageView;
	id _heartLikeFeedItem;
	UICollectionView* _collectionView;

}

@property (nonatomic,readonly) IGHeartView * heartImageView;                   //@synthesize heartImageView=_heartImageView - In the implementation block
@property (nonatomic,retain) id heartLikeFeedItem;                             //@synthesize heartLikeFeedItem=_heartLikeFeedItem - In the implementation block
@property (nonatomic,readonly) UICollectionView * collectionView;              //@synthesize collectionView=_collectionView - In the implementation block
@property (nonatomic,readonly) char usesLegacyAnimation;                       //@synthesize usesLegacyAnimation=_usesLegacyAnimation - In the implementation block
-(char)usesLegacyAnimation;
-(void)setHeartLikeFeedItem:(id)arg1 ;
-(IGHeartView *)heartImageView;
-(id)heartLikeFeedItem;
-(id)initWithCollectionView:(id)arg1 usesLegacyAnimation:(char)arg2 ;
-(void)animateHeartLikeForItem:(id)arg1 atIndex:(int)arg2 ;
-(void)animateHeartLikeForCell:(id)arg1 ;
-(void)updateHeartImageViewLocationToSection:(unsigned)arg1 ;
-(UICollectionView *)collectionView;
@end

