

@interface IGFeedItemTrackingManager : NSObject
+(id)currentModule;
+(char)isMainFeed;
+(void)moreActionSheetForFeedItem:(id)arg1 dismissedWithButtonTitled:(id)arg2 userInfo:(id)arg3 ;
+(void)reportEvent:(id)arg1 immediately:(char)arg2 ;
+(id)sponsoredFeedItemTracker;
+(id)trackerForFeedItem:(id)arg1 ;
+(id)trackingTokenStringTypeForPost:(id)arg1 ;
+(id)trackingTokenStringForPost:(id)arg1 ;
+(char)useNoLatencyLoggingForPost:(id)arg1 ;
+(id)impressionTrackerForFeedItem:(id)arg1 ;
+(void)removeFeedItem:(id)arg1 ;
+(void)hideFeedItem:(id)arg1 extraDictionary:(id)arg2 ;
+(id)websiteClickLinkForFeedItem:(id)arg1 ;
+(char)isAdRatingFeed;
+(char)isCTAAdvertiserProfile;
+(char)isSingleMediaAdSharing;
+(char)isHotOrNotSurvey;
+(char)allowSponsoredPostForFeedItem:(id)arg1 ;
+(id)sponsoredItemImpressionTracker;
+(char)allowOrganicTrackingForFeedItem:(id)arg1 ;
+(id)organicItemImpressionTracker;
+(char)allowExploreTrackingForFeedItem:(id)arg1 ;
+(id)exploreItemImpressionTracker;
+(id)organicFeedItemTracker;
+(id)exploreFeedItemTracker;
+(char)isCommentingFromMainFeed;
-(void)commentButtonTapped:(id)arg1 ;
-(void)surveyWillAppear:(id)arg1 ;
-(void)surveyAnswered:(id)arg1 ;
-(void)surveyPrimerViewDidDismiss:(id)arg1 ;
-(void)brandLiftSurveyWillAppear:(id)arg1 ;
-(void)brandLiftQuestionAnswered:(id)arg1 ;
-(void)brandLiftSurveyPrimerViewDidDismiss:(id)arg1 ;
-(void)brandLiftQuestionDidDismiss:(id)arg1 ;
-(void)didFinishBrowsingWebview:(id)arg1 ;
-(void)feedItemHideReasonSelected:(id)arg1 ;
-(void)commentPosted:(id)arg1 ;
-(void)feedItemLiked:(id)arg1 ;
-(void)feedItemUnliked:(id)arg1 ;
-(void)feedItemDidAppear:(id)arg1 ;
-(void)feedItemDidStartViewing:(id)arg1 ;
-(void)feedItemDidDisappear:(id)arg1 ;
-(void)feedItemDidScrollOffScreen:(id)arg1 ;
-(void)feedItemUserTapped:(id)arg1 ;
-(void)feedItemLocationTapped:(id)arg1 ;
-(void)feedItemURLTapped:(id)arg1 ;
-(void)headerLabelTapped:(id)arg1 ;
-(void)moreButtonTapped:(id)arg1 ;
-(void)feedItemsDidUpdate:(id)arg1 ;
-(void)videoCompleted:(id)arg1 ;
-(void)feedItemReportInappropriate:(id)arg1 ;
-(void)feedItemHideSpam:(id)arg1 ;
-(void)feedItemMediaDidAppearInFull:(id)arg1 ;
-(void)didTakeDirectResponseOverlayAction:(id)arg1 ;
-(void)didTakeDirectResponseAction:(id)arg1 ;
-(void)directResponseActionFailed:(id)arg1 ;
-(void)didTapHeaderTitle:(id)arg1 ;
-(void)didTapHeaderImage:(id)arg1 ;
-(void)didTapMedia:(id)arg1 ;
-(void)videoShouldStartPlaying:(id)arg1 ;
-(void)videoStarted:(id)arg1 ;
-(void)videoDisplayed:(id)arg1 ;
-(void)videoUnpaused:(id)arg1 ;
-(void)videoTapped:(id)arg1 ;
-(void)videoPaused:(id)arg1 ;
-(void)videoViewDidComplete:(id)arg1 ;
-(void)videoDidToggleAudio:(id)arg1 ;
-(void)hotOrNotAdDidWin:(id)arg1 ;
-(void)hotOrNotAdDidLose:(id)arg1 ;
-(void)hotOrNotAdDidDraw:(id)arg1 ;
-(void)hotOrNotAdDidAttempt:(id)arg1 ;
-(void)hotOrNotAdDidSwitch:(id)arg1 ;
-(void)analyticsNoLatencyUploadSuccess:(id)arg1 ;
-(void)includeVideoMetadataFromNotification:(id)arg1 intoEvent:(id)arg2 ;
-(id)stringForAudioToggleReason:(int)arg1 ;
-(id)stringForVideoPlaybackReason:(int)arg1 ;
-(id)stringForVideoStopReason:(int)arg1 ;
-(void)logHotOrNotResultEventForNotification:(id)arg1 eventType:(id)arg2 ;
-(void)logHotOrNotActionEventForNotification:(id)arg1 eventType:(id)arg2 ;
-(void)dealloc;
-(id)init;
@end

