/*
* This header is generated by classdump-dyld 0.7
* on Tuesday, January 19, 2016 at 3:15:01 PM Central Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/4DC55608-3697-420B-B226-BE8BA2A1BD0A/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSString, IGDirectoryFinder;

@interface IGFileFinder : NSObject {

	NSString* _fileName;
	IGDirectoryFinder* _directoryFinder;

}

@property (nonatomic,readonly) NSString * fileName;                              //@synthesize fileName=_fileName - In the implementation block
@property (nonatomic,readonly) IGDirectoryFinder * directoryFinder;              //@synthesize directoryFinder=_directoryFinder - In the implementation block
-(id)initWithFileName:(id)arg1 ;
-(id)cachesFileURL;
-(id)initWithFileName:(id)arg1 directoryFinder:(id)arg2 ;
-(IGDirectoryFinder *)directoryFinder;
-(id)fileURLInDirectory:(id)arg1 ;
-(id)documentsFileURL;
-(id)temporaryFileURL;
-(NSString *)fileName;
@end

