/*
* This header is generated by classdump-dyld 1.0
* on Monday, February 29, 2016 at 3:36:50 PM Central Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/8E0CB1D4-3D23-4350-ABAD-ADD1AC46A9D0/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString, IGDirectoryFinder;

@interface IGFileFinder : NSObject {

	NSString* _fileName;
	IGDirectoryFinder* _directoryFinder;

}

@property (nonatomic,readonly) NSString * fileName;                              //@synthesize fileName=_fileName - In the implementation block
@property (nonatomic,readonly) IGDirectoryFinder * directoryFinder;              //@synthesize directoryFinder=_directoryFinder - In the implementation block
-(id)initWithFileName:(id)arg1 ;
-(id)cachesFileURL;
-(id)initWithFileName:(id)arg1 directoryFinder:(id)arg2 ;
-(IGDirectoryFinder *)directoryFinder;
-(id)fileURLInDirectory:(id)arg1 ;
-(id)documentsFileURL;
-(id)temporaryFileURL;
-(NSString *)fileName;
@end

