/*
* This header is generated by classdump-dyld 0.7
* on Tuesday, October 13, 2015 at 10:19:59 PM Central Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /var/mobile/Containers/Bundle/Application/095E6AAC-0201-41F1-901D-3BA0DA7A9B94/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface IGFilteredImageStore : NSObject
+(void)clearStore;
+(id)cachedImageForImageName:(id)arg1 filterClass:(Class)arg2 ;
+(void)imageForImageName:(id)arg1 filterClass:(Class)arg2 queue:(id)arg3 completion:(/*^block*/id)arg4 ;
+(id)filteredImageForImage:(id)arg1 filterClass:(Class)arg2 ;
+(id)diskStore;
+(id)keyForImageNamed:(id)arg1 filterClass:(Class)arg2 ;
+(char)containsImageForImageName:(id)arg1 filterClass:(Class)arg2 ;
+(id)cache;
+(void)clearCache;
+(id)queue;
@end

