/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, February 16, 2016 at 3:15:36 PM Central Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/C13E072C-E6C1-44DA-8A86-89C97396B2E7/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol IGGenericMegaphoneViewDelegate <NSObject>
@optional
-(void)megaphone:(id)arg1 didTapButton:(id)arg2;

@required
-(void)megaphoneDidDismiss:(id)arg1;
-(void)megaphone:(id)arg1 didOpenURL:(id)arg2;

@end

