/*
* This header is generated by classdump-dyld 1.0
* on Friday, May 13, 2016 at 9:28:48 PM Central Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/6C2D6691-0360-45BF-8623-49F0546803FE/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class IGService, IGGraphQLCache;

@interface IGGraphQLService : NSObject {

	IGService* _service;
	IGGraphQLCache* _cache;

}

@property (nonatomic,readonly) IGService * service;                 //@synthesize service=_service - In the implementation block
@property (nonatomic,readonly) IGGraphQLCache * cache;              //@synthesize cache=_cache - In the implementation block
+(id)graphQLURLFromQueryItems:(id)arg1 queryID:(id)arg2 ;
+(id)graphQLPathFromQueryItems:(id)arg1 queryID:(id)arg2 ;
+(id)baseURL;
-(void)startRequest:(id)arg1 ;
-(void)sendNoAccessTokenErrorWithRequest:(id)arg1 ;
-(id)initWithService:(id)arg1 cache:(id)arg2 ;
-(void)parseResult:(id)arg1 forRequest:(id)arg2 ;
-(void)startNewRequest:(id)arg1 ;
-(id)urlFromQueryItems:(id)arg1 queryID:(id)arg2 ;
-(void)sendRequestWithAccessToken:(id)arg1 url:(id)arg2 graphQLResquest:(id)arg3 ;
-(id)errorForMissingAccessToken;
-(id)requestWithAccessToken:(id)arg1 url:(id)arg2 graphQLRequest:(id)arg3 ;
-(id)errorFromDictionary:(id)arg1 ;
-(id)genCompleteDescriptionFromDictionary:(id)arg1 ;
-(id)init;
-(IGGraphQLCache *)cache;
-(IGService *)service;
@end

