/*
* This header is generated by classdump-dyld 1.0
* on Monday, April 11, 2016 at 7:41:52 PM Central Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /private/var/mobile/Containers/Bundle/Application/F2F7650E-6416-4D13-A52F-83DEE7C62D71/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Instagram/Instagram-Structs.h>
#import <Instagram/IGListItemController.h>
#import <Instagram/IGListItemType.h>

@class NSArray, NSNumberFormatter, NSString;

@interface IGInsightsMediaFeedListItemController : IGListItemController <IGListItemType> {

	NSArray* _mediaBundles;
	int _mediaCellCategory;
	NSNumberFormatter* _commaNumberFormatter;

}

@property (nonatomic,copy) NSArray * mediaBundles;                                  //@synthesize mediaBundles=_mediaBundles - In the implementation block
@property (assign,nonatomic) int mediaCellCategory;                                 //@synthesize mediaCellCategory=_mediaCellCategory - In the implementation block
@property (nonatomic,retain) NSNumberFormatter * commaNumberFormatter;              //@synthesize commaNumberFormatter=_commaNumberFormatter - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)cellClasses;
-(CGSize)estimatedSizeForItemAtIndex:(int)arg1 ;
-(id)cellForItemAtIndex:(int)arg1 ;
-(id)supplementaryViewSource;
-(id)displayDelegate;
-(NSNumberFormatter *)commaNumberFormatter;
-(NSArray *)mediaBundles;
-(void)setMediaBundles:(NSArray *)arg1 ;
-(void)initializeCommaNumberFormatter;
-(CGSize)cellSizeForWidth:(float)arg1 ;
-(int)mediaCellCategory;
-(void)setMediaCellCategory:(int)arg1 ;
-(void)setCommaNumberFormatter:(NSNumberFormatter *)arg1 ;
-(id)init;
-(unsigned)numberOfItems;
-(void)didSelectItemAtIndex:(int)arg1 ;
-(CGSize)sizeForItemAtIndex:(int)arg1 ;
@end

