/*
* This header is generated by classdump-dyld 1.0
* on Monday, February 29, 2016 at 3:36:47 PM Central Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/8E0CB1D4-3D23-4350-ABAD-ADD1AC46A9D0/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Instagram/IGInsightsComponent.h>

@class NSString, NSArray, NSDictionary;

@interface IGInsightsCollectionViewComponent : NSObject <IGInsightsComponent> {

	NSString* _header;
	NSString* _buttonText;
	NSArray* _mediaIDs;
	NSArray* _medias;
	NSDictionary* _buttonQueryItems;

}

@property (nonatomic,copy,readonly) NSString * header;                            //@synthesize header=_header - In the implementation block
@property (nonatomic,copy,readonly) NSString * buttonText;                        //@synthesize buttonText=_buttonText - In the implementation block
@property (nonatomic,copy,readonly) NSArray * mediaIDs;                           //@synthesize mediaIDs=_mediaIDs - In the implementation block
@property (nonatomic,copy,readonly) NSArray * medias;                             //@synthesize medias=_medias - In the implementation block
@property (nonatomic,copy,readonly) NSDictionary * buttonQueryItems;              //@synthesize buttonQueryItems=_buttonQueryItems - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(NSArray *)mediaIDs;
-(NSDictionary *)buttonQueryItems;
-(NSArray *)medias;
-(id)initWithHeader:(id)arg1 buttonText:(id)arg2 buttonQueryItems:(id)arg3 medias:(id)arg4 ;
-(id)style;
-(NSString *)header;
-(NSString *)buttonText;
@end

