/*
* This header is generated by classdump-dyld 0.7
* on Tuesday, September 15, 2015 at 5:29:34 PM Central Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /var/mobile/Containers/Bundle/Application/78EC956B-7ED8-4B50-8025-C2B1976EEC28/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Instagram/Instagram-Structs.h>
#import <UIKit/UIView.h>

@class UIView, UIButton, IGLabel;

@interface IGLibraryAccessPromptView : UIView {

	UIView* _contentView;
	UIButton* _instructionButton;
	IGLabel* _titleLabel;
	IGLabel* _explanationLabel;
	IGLabel* _instructionLabel;

}

@property (nonatomic,retain) UIView * contentView;                      //@synthesize contentView=_contentView - In the implementation block
@property (nonatomic,retain) UIButton * instructionButton;              //@synthesize instructionButton=_instructionButton - In the implementation block
@property (nonatomic,retain) IGLabel * titleLabel;                      //@synthesize titleLabel=_titleLabel - In the implementation block
@property (nonatomic,retain) IGLabel * explanationLabel;                //@synthesize explanationLabel=_explanationLabel - In the implementation block
@property (nonatomic,retain) IGLabel * instructionLabel;                //@synthesize instructionLabel=_instructionLabel - In the implementation block
+(void)showLibraryDeniedAlertView;
-(UIButton *)instructionButton;
-(void)instructionButtonDidTap:(id)arg1 ;
-(void)setInstructionButton:(UIButton *)arg1 ;
-(void)setExplanationLabel:(IGLabel *)arg1 ;
-(void)attachViews;
-(IGLabel *)instructionLabel;
-(void)setInstructionLabel:(IGLabel *)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(UIView *)contentView;
-(void)setContentView:(UIView *)arg1 ;
-(IGLabel *)titleLabel;
-(void)setTitleLabel:(IGLabel *)arg1 ;
-(IGLabel *)explanationLabel;
@end

