/*
* This header is generated by classdump-dyld 0.7
* on Tuesday, January 19, 2016 at 3:15:01 PM Central Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/4DC55608-3697-420B-B226-BE8BA2A1BD0A/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface IGLRUCacheObject : NSObject {

	id _object;
	unsigned _cost;

}

@property (nonatomic,readonly) id object;                  //@synthesize object=_object - In the implementation block
@property (nonatomic,readonly) unsigned cost;              //@synthesize cost=_cost - In the implementation block
-(id)initWithObject:(id)arg1 cost:(unsigned)arg2 ;
-(id)description;
-(id)object;
-(unsigned)cost;
@end

