/*
* This header is generated by classdump-dyld 0.7
* on Tuesday, September 15, 2015 at 5:29:37 PM Central Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /var/mobile/Containers/Bundle/Application/78EC956B-7ED8-4B50-8025-C2B1976EEC28/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Instagram/IGFeedNetworkSource.h>

@class NSArray;

@interface IGMainFeedNetworkSource : IGFeedNetworkSource {

	NSArray* _followAccountList;

}

@property (nonatomic,readonly) NSArray * followAccountList;              //@synthesize followAccountList=_followAccountList - In the implementation block
-(char)fetchDataWithParameters:(id)arg1 ;
-(void)onAppNeedsStateSave;
-(void)onNewItemAvailable:(id)arg1 ;
-(void)deserializeData;
-(void)loadFromFile:(id)arg1 ;
-(void)archiveToFile:(id)arg1 ;
-(void)loadEntriesFromResponse:(id)arg1 clearOut:(char)arg2 ;
-(void)willFetchDataWithParameters:(id)arg1 ;
-(void)onFeedItemDidAppear:(id)arg1 ;
-(void)onAppForeground;
-(void)loadPromotionBannerInfoFromResponse:(id)arg1 ;
-(void)storeLastUnseenAdPK;
-(void)removeUnseenAds;
-(NSArray *)followAccountList;
-(void)dealloc;
-(id)init;
@end

