/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 13, 2015 at 8:03:46 PM Central Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/80FB49E7-07A3-4438-9519-37CDCDE82DE6/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Instagram/Instagram-Structs.h>
#import <Instagram/IGButton.h>

@class UIImageView;

@interface IGMapButton : IGButton {

	UIImageView* _otherImageView;

}

@property (nonatomic,retain) UIImageView * otherImageView;              //@synthesize otherImageView=_otherImageView - In the implementation block
-(id)initWithStyle:(Class)arg1 image:(id)arg2 offset:(CGPoint)arg3 ;
-(UIImageView *)otherImageView;
-(void)setOtherImageView:(UIImageView *)arg1 ;
-(void)setEnabled:(char)arg1 ;
-(id)initWithStyle:(Class)arg1 image:(id)arg2 ;
@end

