/*
* This header is generated by classdump-dyld 0.7
* on Thursday, August 27, 2015 at 8:47:05 PM Central Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /var/mobile/Containers/Bundle/Application/2DC1EEC6-8BB6-4C9F-8658-A819865606D1/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Instagram/Instagram-Structs.h>
#import <UIKit/UIControl.h>

@class NSString, NSArray, UIView;

@interface IGMediaTabBar : UIControl {

	char _selectAlbumOpened;
	NSString* _albumTitle;
	int _selectedIndex;
	NSArray* _buttons;
	UIView* _highlight;

}

@property (nonatomic,copy) NSString * albumTitle;                 //@synthesize albumTitle=_albumTitle - In the implementation block
@property (assign,nonatomic) int selectedIndex;                   //@synthesize selectedIndex=_selectedIndex - In the implementation block
@property (assign,nonatomic) char selectAlbumOpened;              //@synthesize selectAlbumOpened=_selectAlbumOpened - In the implementation block
@property (nonatomic,retain) NSArray * buttons;                   //@synthesize buttons=_buttons - In the implementation block
@property (nonatomic,retain) UIView * highlight;                  //@synthesize highlight=_highlight - In the implementation block
+(float)textInset;
+(float)defaultHeight;
-(float)highlightHeight;
-(char)selectAlbumOpened;
-(void)setSelectAlbumOpened:(char)arg1 ;
-(void)setAlbumTitle:(NSString *)arg1 ;
-(NSString *)albumTitle;
-(id)initWithFrame:(CGRect)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(void)layoutSubviews;
-(int)selectedIndex;
-(void)setSelectedIndex:(int)arg1 ;
-(id)initWithItems:(id)arg1 ;
-(void)setHighlight:(UIView *)arg1 ;
-(UIView *)highlight;
-(NSArray *)buttons;
-(float)itemSize;
-(void)setButtons:(NSArray *)arg1 ;
-(void)buttonWasTapped:(id)arg1 ;
-(float)spacing;
@end

