/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, February 16, 2016 at 3:15:48 PM Central Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/C13E072C-E6C1-44DA-8A86-89C97396B2E7/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Instagram/Instagram-Structs.h>
#import <UIKit/UIView.h>

@class CALayer, UILabel, UIButton;

@interface IGMostRecentRestrictedView : UIView {

	CALayer* _separatorLayer;
	UILabel* _messageLabel;
	UIButton* _learnButton;

}

@property (nonatomic,readonly) CALayer * separatorLayer;              //@synthesize separatorLayer=_separatorLayer - In the implementation block
@property (nonatomic,readonly) UILabel * messageLabel;                //@synthesize messageLabel=_messageLabel - In the implementation block
@property (nonatomic,readonly) UIButton * learnButton;                //@synthesize learnButton=_learnButton - In the implementation block
-(CALayer *)separatorLayer;
-(UIButton *)learnButton;
-(id)initWithFeedName:(id)arg1 ;
-(void)addLearnMoreTarget:(id)arg1 action:(SEL)arg2 ;
-(void)layoutSubviews;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(UILabel *)messageLabel;
@end

