/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 13, 2015 at 8:04:08 PM Central Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/80FB49E7-07A3-4438-9519-37CDCDE82DE6/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Instagram/IGRaindropRankInfo.h>

@interface IGMutableRaindropRankInfo : IGRaindropRankInfo
-(void)setRankToken:(id)arg1 ;
-(void)setRankDisplayRowSize:(id)arg1 ;
-(void)setRankDisplayColumnSize:(id)arg1 ;
-(void)setViewSubType:(int)arg1 ;
-(void)setEntityId:(id)arg1 ;
-(void)setItemRankDisplayOffset:(id)arg1 ;
-(void)setItemRankResponseOffset:(id)arg1 ;
-(void)setSearchQueryText:(id)arg1 ;
-(void)setSearchSessionId:(id)arg1 ;
-(void)setSearchImpressionToken:(id)arg1 ;
-(void)setTimeSpent:(id)arg1 ;
-(void)setSearchType:(int)arg1 ;
-(void)setSectionType:(int)arg1 ;
@end

