/*
* This header is generated by classdump-dyld 0.7
* on Tuesday, October 6, 2015 at 9:46:10 PM Central Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /var/mobile/Containers/Bundle/Application/E660306A-8A68-4027-9100-A800454451FF/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol IGNavSearchBarDelegate <NSObject>
@optional
-(void)searchBarButtonTapped:(id)arg1;
-(void)searchBarWillBeginEditing:(id)arg1;
-(void)searchBarWillEndEditing:(id)arg1;
-(void)searchBarCancelButtonTapped:(id)arg1;
-(void)searchBarReturnKeyTapped:(id)arg1;
-(void)searchBarPeopleIconTapped:(id)arg1;
-(void)searchBar:(id)arg1 textDidChange:(id)arg2;
-(char)searchBarShouldBeginEditing:(id)arg1;
-(char)searchBarShouldEndEditing:(id)arg1;
-(void)searchBarTextDidBeginEditing:(id)arg1;
-(void)searchBarTextDidEndEditing:(id)arg1;
-(char)searchBar:(id)arg1 shouldChangeTextInRange:(NSRange)arg2 replacementText:(id)arg3;

@end

