/*
* This header is generated by classdump-dyld 0.7
* on Tuesday, January 19, 2016 at 3:14:55 PM Central Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/4DC55608-3697-420B-B226-BE8BA2A1BD0A/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSString, NSOrderedSet;

@interface IGNewsDataSourceSection : NSObject {

	NSString* _title;
	NSOrderedSet* _stories;

}

@property (nonatomic,copy) NSString * title;                    //@synthesize title=_title - In the implementation block
@property (nonatomic,copy) NSOrderedSet * stories;              //@synthesize stories=_stories - In the implementation block
+(id)sectionWithTitle:(id)arg1 stories:(id)arg2 ;
-(NSOrderedSet *)stories;
-(void)setStories:(NSOrderedSet *)arg1 ;
-(void)setTitle:(NSString *)arg1 ;
-(NSString *)title;
@end

