/*
* This header is generated by classdump-dyld 0.7
* on Tuesday, October 13, 2015 at 10:19:51 PM Central Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /var/mobile/Containers/Bundle/Application/095E6AAC-0201-41F1-901D-3BA0DA7A9B94/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Instagram/Instagram-Structs.h>
#import <UIKit/UIView.h>

@class IGSimpleButton, UIActivityIndicatorView;

@interface IGPendingRequestView : UIView {

	/*^block*/id _acceptBlock;
	IGSimpleButton* _approveButton;
	IGSimpleButton* _ignoreButton;
	UIActivityIndicatorView* _spinner;

}

@property (nonatomic,copy) id acceptBlock;                                   //@synthesize acceptBlock=_acceptBlock - In the implementation block
@property (nonatomic,retain) IGSimpleButton * approveButton;                 //@synthesize approveButton=_approveButton - In the implementation block
@property (nonatomic,retain) IGSimpleButton * ignoreButton;                  //@synthesize ignoreButton=_ignoreButton - In the implementation block
@property (nonatomic,retain) UIActivityIndicatorView * spinner;              //@synthesize spinner=_spinner - In the implementation block
-(void)setAcceptBlock:(id)arg1 ;
-(IGSimpleButton *)approveButton;
-(void)onApproveButtonTapped;
-(void)onIgnoreButtonTapped;
-(id)acceptBlock;
-(void)setApproveButton:(IGSimpleButton *)arg1 ;
-(void)setSpinner:(UIActivityIndicatorView *)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(id)init;
-(void)layoutSubviews;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(UIActivityIndicatorView *)spinner;
-(void)setIgnoreButton:(IGSimpleButton *)arg1 ;
-(IGSimpleButton *)ignoreButton;
@end

