/*
* This header is generated by classdump-dyld 1.0
* on Monday, February 29, 2016 at 3:36:39 PM Central Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/8E0CB1D4-3D23-4350-ABAD-ADD1AC46A9D0/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Instagram/IGFeedViewController_DEPRECATED.h>

@class IGFeedItem;

@interface IGPivotSingleFeedViewController : IGFeedViewController_DEPRECATED {

	IGFeedItem* _item;
	int _entryPoint;
	char _shouldShowRefreshButton;

}

@property (assign,nonatomic) char shouldShowRefreshButton;              //@synthesize shouldShowRefreshButton=_shouldShowRefreshButton - In the implementation block
-(id)analyticsModule;
-(id)initWithFeedItem:(id)arg1 entryPoint:(int)arg2 ;
-(void)displayPivots:(id)arg1 ;
-(int)entryPointMapping;
-(char)showRefreshButton;
-(char)shouldShowRefreshButton;
-(void)setShouldShowRefreshButton:(char)arg1 ;
@end

