/*
* This header is generated by classdump-dyld 1.0
* on Friday, May 13, 2016 at 9:28:40 PM Central Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/6C2D6691-0360-45BF-8623-49F0546803FE/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

@class UIImageView, NSString, UIColor;


@protocol IGPickerCellType <NSObject>
@property (nonatomic,readonly) UIImageView * iconView; 
@property (nonatomic,copy) NSString * title; 
@property (assign,nonatomic) char showsHighlightIndicator; 
@property (nonatomic,retain) UIColor * highlightIndicatorColor; 
@required
+(CGSize*)cellSizeToFit:(CGSize)arg1;
-(char)showsHighlightIndicator;
-(void)setShowsHighlightIndicator:(char)arg1;
-(void)setTitle:(id)arg1;
-(NSString *)title;
-(UIImageView *)iconView;
-(UIColor *)highlightIndicatorColor;
-(void)setHighlightIndicatorColor:(id)arg1;

@end

