/*
* This header is generated by classdump-dyld 0.7
* on Tuesday, January 19, 2016 at 3:14:54 PM Central Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/4DC55608-3697-420B-B226-BE8BA2A1BD0A/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Instagram/IGNavigationController.h>

@class IGPopoverController;

@interface IGPopoverNavigationController : IGNavigationController {

	IGPopoverController* _containerController;

}

@property (assign,nonatomic,__weak) IGPopoverController * containerController;              //@synthesize containerController=_containerController - In the implementation block
-(IGPopoverController *)containerController;
-(void)setContainerController:(IGPopoverController *)arg1 ;
-(void)dismissViewControllerAnimated:(char)arg1 completion:(/*^block*/id)arg2 ;
@end

