/*
* This header is generated by classdump-dyld 0.7
* on Tuesday, October 6, 2015 at 9:46:11 PM Central Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /var/mobile/Containers/Bundle/Application/E660306A-8A68-4027-9100-A800454451FF/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Instagram/Instagram-Structs.h>
#import <UIKit/UIView.h>
#import <Instagram/IGTabBarButtonSupplementaryViewProtocol.h>

@class IGProfilePictureImageView, NSString;

@interface IGProfilePictureTabBarSupplementaryView : UIView <IGTabBarButtonSupplementaryViewProtocol> {

	IGProfilePictureImageView* _profilePicImageView;

}

@property (nonatomic,retain) IGProfilePictureImageView * profilePicImageView;              //@synthesize profilePicImageView=_profilePicImageView - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(IGProfilePictureImageView *)profilePicImageView;
-(void)setProfilePicImageView:(IGProfilePictureImageView *)arg1 ;
-(id)initWithFrame:(CGRect)arg1 profilePictureImageView:(id)arg2 ;
-(void)tabBarButtonUpdatedWithIsSelected:(char)arg1 ;
-(void)layoutSubviews;
@end

