/*
* This header is generated by classdump-dyld 0.7
* on Thursday, August 27, 2015 at 8:47:14 PM Central Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /var/mobile/Containers/Bundle/Application/2DC1EEC6-8BB6-4C9F-8658-A819865606D1/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Instagram/IGDirectedPostViewControllerDelegate.h>

@class NSMutableArray, NSString;

@interface IGPushHelper : NSObject <IGDirectedPostViewControllerDelegate> {

	NSMutableArray* _cachedFeedItems;
	char _freshAppInstall;

}

@property (assign,getter=isFreshAppInstall,nonatomic) char freshAppInstall;              //@synthesize freshAppInstall=_freshAppInstall - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)sharedPushHelper;
-(char)isFreshAppInstall;
-(void)postViewControllerWantsDismissal:(id)arg1 ;
-(id)categoriesForPushNotifications;
-(char)appHasPushPermissions;
-(char)appHasAskedSystemForPushPermissions;
-(char)isTimeToPromptForPushPermissions;
-(id)convertTokenToDeviceID:(id)arg1 ;
-(void)handleBackgroundPushNotification:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)handleForegroundPushNotification:(id)arg1 ;
-(void)showNotificationBarWithUserInfo:(id)arg1 andPostPK:(id)arg2 ;
-(void)showNotificationBarWithUserInfo:(id)arg1 andThreadId:(id)arg2 ;
-(void)onBackTapped:(id)arg1 ;
-(void)startPushRegistrationWithForce:(char)arg1 ;
-(char)shouldShowPushMegaphone;
-(void)registerForPushWithToken:(id)arg1 ;
-(void)handlePushNotification:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)clearFeedItemCache;
-(void)handleActionWithIdentifier:(id)arg1 forRemoteNotification:(id)arg2 completionHandler:(/*^block*/id)arg3 ;
-(void)setFreshAppInstall:(char)arg1 ;
-(id)init;
@end

