/*
* This header is generated by classdump-dyld 0.7
* on Tuesday, September 15, 2015 at 5:29:41 PM Central Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /var/mobile/Containers/Bundle/Application/78EC956B-7ED8-4B50-8025-C2B1976EEC28/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSDictionary, NSString, IGUser;

@interface IGQEExperimentManager : NSObject {

	double _lastSyncTime;
	NSDictionary* _experiments;
	NSDictionary* _cachedPayload;
	char _wantsColdStart;
	NSString* _cacheDirectory;
	IGUser* _previousUser;

}

@property (nonatomic,readonly) NSString * cacheFilePath; 
+(char)exposeValueForBoolExperiment:(id)arg1 ;
+(id)exposeValueForExperiment:(id)arg1 parameterName:(id)arg2 ;
+(id)experiments;
+(void)refreshExperimentsIfNecessary;
+(char)wantsColdStart;
+(id)experimentForKey:(id)arg1 ;
+(void)disableExperiments;
+(id)sharedInstance;
-(id)experiments;
-(void)loginStateChange;
-(void)loadDefaultExperiments;
-(void)loadCachedExperiments;
-(void)refreshExperimentsForced;
-(NSString *)cacheFilePath;
-(char)updateExperimentsWithPayload:(id)arg1 useDeviceId:(char)arg2 ;
-(void)refreshExperimentsIfNecessary;
-(char)wantsColdStart;
-(id)experimentForKey:(id)arg1 ;
-(void)dealloc;
-(id)init;
@end

