/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 13, 2015 at 8:03:50 PM Central Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/80FB49E7-07A3-4438-9519-37CDCDE82DE6/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

@class UIImage, NSData;


@protocol IGQuickCamOutputAsset <NSObject>
@property (nonatomic,retain) UIImage * displayImage; 
@property (nonatomic,retain) UIImage * croppedImage; 
@property (assign,nonatomic) char isFromLibrary; 
@property (assign,nonatomic) int devicePosition; 
@property (nonatomic,readonly) NSData * imageData; 
@property (nonatomic,readonly) char isPhoto; 
@required
-(char)isFromLibrary;
-(int)devicePosition;
-(void)setDevicePosition:(int)arg1;
-(UIImage *)croppedImage;
-(void)setDisplayImage:(id)arg1;
-(void)setCroppedImage:(id)arg1;
-(void)setIsFromLibrary:(char)arg1;
-(NSData *)imageData;
-(char)isPhoto;
-(UIImage *)displayImage;

@end

