/*
* This header is generated by classdump-dyld 0.7
* on Tuesday, September 15, 2015 at 5:29:47 PM Central Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /var/mobile/Containers/Bundle/Application/78EC956B-7ED8-4B50-8025-C2B1976EEC28/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Instagram/Instagram-Structs.h>
#import <Instagram/TBaseStruct.h>
#import <Instagram/TBase.h>
#import <Instagram/NSCoding.h>

@class NSString;

@interface IGRaindropClusterEvent : TBaseStruct <TBase, NSCoding> {

	NSString* __thrift_clusterId;
	NSString* __thrift_clusterUserId;
	NSString* __thrift_clusterPosition;
	NSString* __thrift_clusterUserPosition;
	int __thrift_clusterEventType;
	long long __thrift_errorStatusCode;
	NSString* __thrift_errorMessage;
	char __thrift_clusterId_set;
	char __thrift_clusterUserId_set;
	char __thrift_clusterPosition_set;
	char __thrift_clusterUserPosition_set;
	char __thrift_clusterEventType_set;
	char __thrift_errorStatusCode_set;
	char __thrift_errorMessage_set;

}

@property (nonatomic,retain) NSString * clusterId; 
@property (nonatomic,retain) NSString * clusterUserId; 
@property (nonatomic,retain) NSString * clusterPosition; 
@property (nonatomic,retain) NSString * clusterUserPosition; 
@property (assign,nonatomic) int clusterEventType; 
@property (assign,nonatomic) long long errorStatusCode; 
@property (nonatomic,retain) NSString * errorMessage; 
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)toDict;
-(void)setClusterEventType:(int)arg1 ;
-(void)setErrorStatusCode:(long long)arg1 ;
-(void)setClusterId:(NSString *)arg1 ;
-(void)setClusterPosition:(NSString *)arg1 ;
-(void)setClusterUserId:(NSString *)arg1 ;
-(void)setClusterUserPosition:(NSString *)arg1 ;
-(void)read:(id)arg1 ;
-(char)errorMessageIsSet;
-(void)unsetErrorMessage;
-(id)initWithClusterId:(id)arg1 clusterUserId:(id)arg2 clusterPosition:(id)arg3 clusterUserPosition:(id)arg4 clusterEventType:(int)arg5 errorStatusCode:(long long)arg6 errorMessage:(id)arg7 ;
-(NSString *)clusterId;
-(char)clusterIdIsSet;
-(void)unsetClusterId;
-(NSString *)clusterUserId;
-(char)clusterUserIdIsSet;
-(void)unsetClusterUserId;
-(NSString *)clusterPosition;
-(char)clusterPositionIsSet;
-(void)unsetClusterPosition;
-(NSString *)clusterUserPosition;
-(char)clusterUserPositionIsSet;
-(void)unsetClusterUserPosition;
-(int)clusterEventType;
-(char)clusterEventTypeIsSet;
-(void)unsetClusterEventType;
-(char)errorStatusCodeIsSet;
-(void)unsetErrorStatusCode;
-(char)makeImmutable;
-(long long)errorStatusCode;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(id)init;
-(NSString *)description;
-(void)validate;
-(id)mutableCopyWithZone:(NSZone*)arg1 ;
-(void)write:(id)arg1 ;
-(void)setErrorMessage:(NSString *)arg1 ;
-(NSString *)errorMessage;
@end

