/*
* This header is generated by classdump-dyld 0.7
* on Monday, October 26, 2015 at 9:24:51 PM Central Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/21A1C6E8-DEFC-46E0-A287-C60E9807B6FE/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Instagram/Instagram-Structs.h>
#import <Instagram/TBaseStruct.h>
#import <Instagram/TBase.h>
#import <libobjc.A.dylib/NSCoding.h>

@class NSString, NSMutableArray;

@interface IGRaindropTapLocationResultEvent : TBaseStruct <TBase, NSCoding> {

	long long __thrift_selectedPosition;
	NSString* __thrift_placeId;
	NSMutableArray* __thrift_resultList;
	NSString* __thrift_searchSessionId;
	char __thrift_selectedPosition_set;
	char __thrift_placeId_set;
	char __thrift_resultList_set;
	char __thrift_searchSessionId_set;

}

@property (assign,nonatomic) long long selectedPosition; 
@property (nonatomic,retain) NSString * placeId; 
@property (nonatomic,retain) NSMutableArray * resultList; 
@property (nonatomic,retain) NSString * searchSessionId; 
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)toDict;
-(NSString *)searchSessionId;
-(void)setSearchSessionId:(NSString *)arg1 ;
-(void)read:(id)arg1 ;
-(char)placeIdIsSet;
-(void)unsetPlaceId;
-(char)searchSessionIdIsSet;
-(void)unsetSearchSessionId;
-(char)selectedPositionIsSet;
-(void)unsetSelectedPosition;
-(void)setResultList:(NSMutableArray *)arg1 ;
-(NSMutableArray *)resultList;
-(char)resultListIsSet;
-(void)unsetResultList;
-(id)initWithSelectedPosition:(long long)arg1 placeId:(id)arg2 resultList:(NSMutableArray*)arg3 searchSessionId:(id)arg4 ;
-(char)makeImmutable;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(id)init;
-(NSString *)description;
-(id)mutableCopyWithZone:(NSZone*)arg1 ;
-(void)validate;
-(void)write:(id)arg1 ;
-(long long)selectedPosition;
-(void)setSelectedPosition:(long long)arg1 ;
-(NSString *)placeId;
-(void)setPlaceId:(NSString *)arg1 ;
@end

