/*
* This header is generated by classdump-dyld 0.7
* on Tuesday, September 15, 2015 at 5:29:47 PM Central Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /var/mobile/Containers/Bundle/Application/78EC956B-7ED8-4B50-8025-C2B1976EEC28/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Instagram/Instagram-Structs.h>
#import <Instagram/TBaseStruct.h>
#import <Instagram/TBase.h>
#import <Instagram/NSCoding.h>

@class NSString;

@interface IGRaindropMarquee : TBaseStruct <TBase, NSCoding> {

	NSString* __thrift_title;
	NSString* __thrift_type;
	NSString* __thrift_id;
	char __thrift_title_set;
	char __thrift_type_set;
	char __thrift_id_set;

}

@property (nonatomic,retain) NSString * title; 
@property (nonatomic,retain) NSString * type; 
@property (nonatomic,retain) NSString * id; 
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)toDict;
-(void)read:(id)arg1 ;
-(id)initWithTitle:(id)arg1 type:(id)arg2 id:(id)arg3 ;
-(char)titleIsSet;
-(void)unsetTitle;
-(char)typeIsSet;
-(void)unsetType;
-(char)idIsSet;
-(void)unsetId;
-(char)makeImmutable;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(id)init;
-(void)setTitle:(NSString *)arg1 ;
-(NSString *)description;
-(void)setType:(NSString *)arg1 ;
-(NSString *)type;
-(NSString *)title;
-(void)validate;
-(id)mutableCopyWithZone:(NSZone*)arg1 ;
-(void)write:(id)arg1 ;
-(NSString *)id;
-(void)setId:(NSString *)arg1 ;
@end

