/*
* This header is generated by classdump-dyld 1.0
* on Monday, April 11, 2016 at 7:41:57 PM Central Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /private/var/mobile/Containers/Bundle/Application/F2F7650E-6416-4D13-A52F-83DEE7C62D71/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Instagram/Instagram-Structs.h>
#import <Instagram/TBaseStruct.h>

@class NSString, NSNumber;

@interface IGRaindropSearchEvent : TBaseStruct {

	NSString* __thrift_searchQueryText;
	NSNumber* __thrift_wasSearchButtonTaped;
	int __thrift_searchType;
	NSNumber* __thrift_rttInMillis;

}
-(id)toDict;
-(id)initWithSearchQueryText:(id)arg1 wasSearchButtonTaped:(id)arg2 searchType:(int)arg3 rttInMillis:(id)arg4 ;
-(id)init;
-(id)description;
-(id)mutableCopyWithZone:(NSZone*)arg1 ;
-(void)write:(id)arg1 ;
-(int)searchType;
@end

