/*
* This header is generated by classdump-dyld 0.7
* on Tuesday, January 19, 2016 at 3:15:02 PM Central Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/4DC55608-3697-420B-B226-BE8BA2A1BD0A/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Instagram/Instagram-Structs.h>
#import <Instagram/TBaseStruct.h>

@class NSString, NSNumber, IGRaindropPlace;

@interface IGRaindropResultId : TBaseStruct {

	NSString* __thrift_hashtagId;
	NSNumber* __thrift_userId;
	IGRaindropPlace* __thrift_placeId_DEPRECATED;
	NSString* __thrift_placeId;

}
-(id)toDict;
-(id)initWithPlaceId:(id)arg1 ;
-(id)initWithHashtagId:(id)arg1 ;
-(id)initWithUserId:(id)arg1 ;
-(id)initWithPlaceId_DEPRECATED:(id)arg1 ;
-(id)placeId_DEPRECATED;
-(id)init;
-(id)description;
-(id)mutableCopyWithZone:(NSZone*)arg1 ;
-(void)write:(id)arg1 ;
-(id)userId;
-(id)placeId;
@end

