/*
* This header is generated by classdump-dyld 1.0
* on Friday, May 13, 2016 at 9:28:35 PM Central Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/6C2D6691-0360-45BF-8623-49F0546803FE/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Instagram/Instagram-Structs.h>
#import <Instagram/TBaseStruct.h>

@class NSString, NSNumber;

@interface IGRaindropSearchQuery : TBaseStruct {

	NSString* __thrift_searchQueryText;
	NSNumber* __thrift_timestamp;
	NSNumber* __thrift_rttInMillis;

}
-(id)searchQueryText;
-(id)toDict;
-(id)initWithSearchQueryText:(id)arg1 timestamp:(id)arg2 rttInMillis:(id)arg3 ;
-(id)init;
-(id)description;
-(id)timestamp;
-(id)mutableCopyWithZone:(NSZone*)arg1 ;
-(void)write:(id)arg1 ;
@end

