/*
* This header is generated by classdump-dyld 0.7
* on Tuesday, January 19, 2016 at 3:15:00 PM Central Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/4DC55608-3697-420B-B226-BE8BA2A1BD0A/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol IGRetroRegistrationLoginViewControllerDelegate <NSObject>
@required
-(char)loginViewControllerIsSwitchingUsers:(id)arg1;
-(void)loginViewControllerDidTapLoginButton:(id)arg1;
-(void)loginViewController:(id)arg1 didTapOnLoginHelperButtonWithUsername:(id)arg2;
-(void)loginViewControllerDidTapSignUpButton:(id)arg1;
-(void)loginViewControllerWantsToDismiss:(id)arg1;
-(void)loginViewController:(id)arg1 didTapOnURL:(id)arg2;
-(void)loginViewController:(id)arg1 resetPasswordWithViewController:(id)arg2;
-(void)loginViewController:(id)arg1 proceedTwoFactorWithInfo:(id)arg2;
-(void)loginViewController:(id)arg1 userEmailTakenAutoLoginWithLoggedInDict:(id)arg2;
-(void)loginViewController:(id)arg1 proceedRegistrationWithFBInfo:(id)arg2;

@end

