/*
* This header is generated by classdump-dyld 1.0
* on Friday, May 13, 2016 at 9:28:51 PM Central Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/6C2D6691-0360-45BF-8623-49F0546803FE/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol IGRetroRegistrationSignInHelperViewControllerDelegate <NSObject>
@required
-(void)signInHelperViewController:(id)arg1 didTapOnURL:(id)arg2;
-(char)signInHelperViewControllerIsSwitchingUsers:(id)arg1;
-(void)signInHelperViewControllerDidTapBackButton:(id)arg1;
-(void)signInHelperViewController:(id)arg1 didRequestSupportWithUsername:(id)arg2;
-(void)signInHelperViewControllerDidTapLogInButton:(id)arg1;
-(void)signInHelperViewControllerDidTapSignUpButton:(id)arg1;
-(void)signInHelperViewController:(id)arg1 userEmailTakenAutoLoginWithLoggedInDicted:(id)arg2;
-(void)signInHelperViewController:(id)arg1 willProceedRegistrationWithFBInfo:(id)arg2 facebookAccessToken:(id)arg3;
-(void)signInHelperViewController:(id)arg1 proceedTwoFactorWithInfo:(id)arg2 facebookAccessToken:(id)arg3;
-(void)signInHelperViewController:(id)arg1 resetPasswordWithViewController:(id)arg2;

@end

