/*
* This header is generated by classdump-dyld 0.7
* on Thursday, August 27, 2015 at 8:51:31 PM Central Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /var/mobile/Containers/Bundle/Application/2DC1EEC6-8BB6-4C9F-8658-A819865606D1/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Instagram/IGGroupedTableViewController.h>
#import <Instagram/IGCoreTextLinkHandler.h>

@class IGUser, NSString, UIView;

@interface IGResetPasswordOptionsViewController : IGGroupedTableViewController <IGCoreTextLinkHandler> {

	int _emailRequestState;
	int _smsRequestState;
	int _lastSentMedium;
	char _hasValidPhone;
	IGUser* _user;
	NSString* _userEmail;
	UIView* _emailConformationFooterView;
	UIView* _smsConfirmationFooterView;

}

@property (nonatomic,retain) IGUser * user;                                     //@synthesize user=_user - In the implementation block
@property (nonatomic,copy) NSString * userEmail;                                //@synthesize userEmail=_userEmail - In the implementation block
@property (assign,nonatomic) char hasValidPhone;                                //@synthesize hasValidPhone=_hasValidPhone - In the implementation block
@property (nonatomic,retain) UIView * emailConformationFooterView;              //@synthesize emailConformationFooterView=_emailConformationFooterView - In the implementation block
@property (nonatomic,retain) UIView * smsConfirmationFooterView;                //@synthesize smsConfirmationFooterView=_smsConfirmationFooterView - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)coreTextView:(id)arg1 didTapOnString:(id)arg2 URL:(id)arg3 ;
-(char)hasValidPhone;
-(id)emailConfirmationView;
-(id)smsConfirmationView;
-(void)setHasValidPhone:(char)arg1 ;
-(UIView *)emailConformationFooterView;
-(void)setEmailConformationFooterView:(UIView *)arg1 ;
-(UIView *)smsConfirmationFooterView;
-(void)setSmsConfirmationFooterView:(UIView *)arg1 ;
-(id)init;
-(float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2 ;
-(float)tableView:(id)arg1 heightForFooterInSection:(int)arg2 ;
-(id)tableView:(id)arg1 viewForFooterInSection:(int)arg2 ;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2 ;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(int)numberOfSectionsInTableView:(id)arg1 ;
-(void)viewWillAppear:(char)arg1 ;
-(void)viewDidLoad;
-(IGUser *)user;
-(void)setUser:(IGUser *)arg1 ;
-(void)setUserEmail:(NSString *)arg1 ;
-(NSString *)userEmail;
@end

