/*
* This header is generated by classdump-dyld 0.7
* on Tuesday, February 2, 2016 at 7:26:34 PM Central Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3AACC7FB-0FE9-4871-925D-3A035BF7F4E1/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Instagram/IGRegistrationWelcomeControllerBase.h>
#import <Instagram/IGRegistrationSignUpViewBaseDelegate.h>

@class IGRegistrationSignUpViewThreeButtons, NSString;

@interface IGRegistrationWelcomeControllerThreeButtons : IGRegistrationWelcomeControllerBase <IGRegistrationSignUpViewBaseDelegate> {

	IGRegistrationSignUpViewThreeButtons* _signUpView;

}

@property (nonatomic,retain) IGRegistrationSignUpViewThreeButtons * signUpView; 
@property (assign,nonatomic,__weak) id<IGRegistrationWelcomeControllerThreeButtonsDelegate> delegate; 
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)userWillProceedFromSignUpView:(id)arg1 withUserInfo:(id)arg2 ;
-(IGRegistrationSignUpViewThreeButtons *)signUpView;
-(void)logInWithFacebookTapped;
-(void)setRegistrationMode:(int)arg1 ;
-(void)dealloc;
@end

