/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, February 16, 2016 at 3:16:00 PM Central Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/C13E072C-E6C1-44DA-8A86-89C97396B2E7/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Instagram/Instagram-Structs.h>
#import <UIKit/UIScrollView.h>

@class UIButton, IGRetroRegistrationTextField, IGRetroRegistrationPhoneNumberField, IGRetroRegistrationNextButton, IGTextField, IGCoreTextView, IGFacebookButton, UIImageView, UILabel, IGRetroRegistrationFacebookButtonSeperator;

@interface IGRetroRegistrationSignInHelperScrollView : UIScrollView {

	UIButton* _switchButton;
	IGRetroRegistrationTextField* _emailField;
	IGRetroRegistrationPhoneNumberField* _phoneNumberField;
	IGRetroRegistrationNextButton* _sendButton;
	IGTextField* _inputView;
	int _inputMode;
	IGCoreTextView* _loginHelperView;
	IGFacebookButton* _facebookButton;
	UIImageView* _iconView;
	UILabel* _titleLabel;
	UILabel* _descriptionLabel;
	IGRetroRegistrationFacebookButtonSeperator* _facebookButtonSeparator;

}

@property (nonatomic,retain) UIButton * switchButton;                                                           //@synthesize switchButton=_switchButton - In the implementation block
@property (nonatomic,retain) IGRetroRegistrationTextField * emailField;                                         //@synthesize emailField=_emailField - In the implementation block
@property (nonatomic,retain) IGRetroRegistrationPhoneNumberField * phoneNumberField;                            //@synthesize phoneNumberField=_phoneNumberField - In the implementation block
@property (nonatomic,retain) IGRetroRegistrationNextButton * sendButton;                                        //@synthesize sendButton=_sendButton - In the implementation block
@property (nonatomic,retain) IGTextField * inputView;                                                           //@synthesize inputView=_inputView - In the implementation block
@property (assign,nonatomic) int inputMode;                                                                     //@synthesize inputMode=_inputMode - In the implementation block
@property (nonatomic,retain) IGCoreTextView * loginHelperView;                                                  //@synthesize loginHelperView=_loginHelperView - In the implementation block
@property (nonatomic,retain) IGFacebookButton * facebookButton;                                                 //@synthesize facebookButton=_facebookButton - In the implementation block
@property (nonatomic,retain) UIImageView * iconView;                                                            //@synthesize iconView=_iconView - In the implementation block
@property (nonatomic,retain) UILabel * titleLabel;                                                              //@synthesize titleLabel=_titleLabel - In the implementation block
@property (nonatomic,retain) UILabel * descriptionLabel;                                                        //@synthesize descriptionLabel=_descriptionLabel - In the implementation block
@property (nonatomic,retain) IGRetroRegistrationFacebookButtonSeperator * facebookButtonSeparator;              //@synthesize facebookButtonSeparator=_facebookButtonSeparator - In the implementation block
+(id)createTitleLabel;
+(id)createDescriptionLabel;
+(id)createIconView;
+(id)createSwitchButton;
+(id)createEmailField;
+(id)createPhoneNumberField;
+(id)createSendButton;
+(id)createLoginHelperView;
+(id)createFacebookButton;
-(IGRetroRegistrationTextField *)emailField;
-(void)setEmailField:(IGRetroRegistrationTextField *)arg1 ;
-(IGRetroRegistrationFacebookButtonSeperator *)facebookButtonSeparator;
-(IGFacebookButton *)facebookButton;
-(void)setFacebookButton:(IGFacebookButton *)arg1 ;
-(void)setFacebookButtonSeparator:(IGRetroRegistrationFacebookButtonSeperator *)arg1 ;
-(IGCoreTextView *)loginHelperView;
-(void)setLoginHelperView:(IGCoreTextView *)arg1 ;
-(IGRetroRegistrationPhoneNumberField *)phoneNumberField;
-(void)setPhoneNumberField:(IGRetroRegistrationPhoneNumberField *)arg1 ;
-(void)switchToEmailView;
-(UIButton *)switchButton;
-(void)switchToPhoneNumberView;
-(void)setSwitchButton:(UIButton *)arg1 ;
-(UILabel *)descriptionLabel;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
-(UILabel *)titleLabel;
-(IGTextField *)inputView;
-(void)setInputView:(IGTextField *)arg1 ;
-(void)setInputMode:(int)arg1 ;
-(int)inputMode;
-(void)setTitleLabel:(UILabel *)arg1 ;
-(UIImageView *)iconView;
-(void)setIconView:(UIImageView *)arg1 ;
-(IGRetroRegistrationNextButton *)sendButton;
-(void)setSendButton:(IGRetroRegistrationNextButton *)arg1 ;
-(void)setDescriptionLabel:(UILabel *)arg1 ;
@end

