/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 13, 2015 at 8:04:06 PM Central Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/80FB49E7-07A3-4438-9519-37CDCDE82DE6/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Instagram/Instagram-Structs.h>
#import <Instagram/IGRegistrationSignUpViewBase.h>

@class UIButton;

@interface IGRegistrationSignUpViewThreeButtons : IGRegistrationSignUpViewBase {

	char _hasSetConstraints;
	UIButton* _emailButton;
	UIButton* _phoneNumberButton;

}

@property (nonatomic,retain) UIButton * emailButton;                    //@synthesize emailButton=_emailButton - In the implementation block
@property (nonatomic,retain) UIButton * phoneNumberButton;              //@synthesize phoneNumberButton=_phoneNumberButton - In the implementation block
@property (assign,nonatomic) char hasSetConstraints;                    //@synthesize hasSetConstraints=_hasSetConstraints - In the implementation block
-(char)hasSetConstraints;
-(void)setHasSetConstraints:(char)arg1 ;
-(void)setupEmailButton;
-(void)setupPhoneNumberButton;
-(UIButton *)emailButton;
-(UIButton *)phoneNumberButton;
-(void)emailButtonPressed;
-(void)phoneNumberButtonPressed;
-(void)setEmailButton:(UIButton *)arg1 ;
-(void)setPhoneNumberButton:(UIButton *)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)updateConstraints;
@end

