/*
* This header is generated by classdump-dyld 0.7
* on Thursday, August 27, 2015 at 8:51:31 PM Central Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /var/mobile/Containers/Bundle/Application/2DC1EEC6-8BB6-4C9F-8658-A819865606D1/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UIView.h>

@class UIImageView, UILabel;

@interface IGRegistrationHeaderView : UIView {

	UIImageView* _backgroundImageView;
	UILabel* _instructionLabel;

}

@property (nonatomic,retain) UIImageView * backgroundImageView;              //@synthesize backgroundImageView=_backgroundImageView - In the implementation block
@property (nonatomic,retain) UILabel * instructionLabel;                     //@synthesize instructionLabel=_instructionLabel - In the implementation block
-(UILabel *)instructionLabel;
-(void)setInstructionLabel:(UILabel *)arg1 ;
-(id)initWithBackgroundImage:(id)arg1 instructionalText:(id)arg2 height:(float)arg3 ;
-(id)init;
-(void)layoutSubviews;
-(UIImageView *)backgroundImageView;
-(void)setBackgroundImageView:(UIImageView *)arg1 ;
@end

