/*
* This header is generated by classdump-dyld 0.7
* on Tuesday, February 2, 2016 at 7:26:34 PM Central Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3AACC7FB-0FE9-4871-925D-3A035BF7F4E1/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class UIViewController;

@interface IGRetroRegistrationLoginHelper : NSObject {

	UIViewController* _viewController;

}

@property (assign,nonatomic,__weak) UIViewController * viewController;              //@synthesize viewController=_viewController - In the implementation block
-(void)sendPasswordResetEmailForUser:(id)arg1 ;
-(void)displayToastMessage:(id)arg1 ;
-(void)sendLoginEmailForUsername:(id)arg1 ;
-(void)sendLoginEmailForUsernameOrEmail:(id)arg1 ;
-(void)lookupEmailForUsername:(id)arg1 ;
-(void)setViewController:(UIViewController *)arg1 ;
-(UIViewController *)viewController;
-(id)initWithViewController:(id)arg1 ;
@end

