/*
* This header is generated by classdump-dyld 1.0
* on Friday, May 13, 2016 at 9:28:51 PM Central Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/6C2D6691-0360-45BF-8623-49F0546803FE/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol IGRetroRegistrationFindFriendsViewControllerDelegate <NSObject>
@required
-(void)findFriendsController:(id)arg1 wantsToUpdateToFollowCount:(int)arg2;
-(void)findFriendsControllerNextButtonTapped:(id)arg1;
-(void)findFriendsControllerSkipButtonTapped:(id)arg1;
-(void)findFriendsController:(id)arg1 wantsToPresentViewController:(id)arg2 animated:(char)arg3 completion:(/*^block*/id)arg4;
-(void)findFriendsController:(id)arg1 wantsToDismissViewControllerAnimated:(char)arg2 completion:(/*^block*/id)arg3;
-(void)findFriendsController:(id)arg1 wasTappedOnURL:(id)arg2;

@end

