/*
* This header is generated by classdump-dyld 0.7
* on Tuesday, September 15, 2015 at 5:29:45 PM Central Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /var/mobile/Containers/Bundle/Application/78EC956B-7ED8-4B50-8025-C2B1976EEC28/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol IGRegistrationFlowControllerDelegate <NSObject>
@required
-(void)flowController:(id)arg1 didFinishRegistrationWithLoggedInDict:(id)arg2;
-(void)flowController:(id)arg1 continueRegistrationToStep:(id)arg2 inboundAnimation:(int)arg3 outboundAnimation:(int)arg4;
-(void)flowController:(id)arg1 shouldRegisterWithFacebookInformation:(id)arg2;
-(void)flowController:(id)arg1 willResetPasswordWithViewController:(id)arg2;
-(void)flowController:(id)arg1 willPresentNavigationController:(id)arg2;
-(char)flowControllerIsSwitchingUsers:(id)arg1;

@end

