/*
* This header is generated by classdump-dyld 0.7
* on Thursday, August 27, 2015 at 8:47:22 PM Central Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /var/mobile/Containers/Bundle/Application/2DC1EEC6-8BB6-4C9F-8658-A819865606D1/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Instagram/IGSearchSectionController.h>

@class IGSearchResultsViewController, NSOrderedSet, NSArray, NSString;

@interface IGSearchResultsSectionController : NSObject <IGSearchSectionController> {

	IGSearchResultsViewController* _viewController;
	NSOrderedSet* _items;
	NSArray* _itemControllers;

}

@property (nonatomic,__weak,readonly) IGSearchResultsViewController * viewController;              //@synthesize viewController=_viewController - In the implementation block
@property (nonatomic,readonly) NSOrderedSet * items;                                               //@synthesize items=_items - In the implementation block
@property (nonatomic,readonly) NSArray * itemControllers;                                          //@synthesize itemControllers=_itemControllers - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)itemControllerForItem:(id)arg1 ;
-(NSArray *)itemControllers;
-(id)initWithItems:(id)arg1 viewController:(id)arg2 ;
-(id)initWithArrayOfItems:(id)arg1 viewController:(id)arg2 ;
-(id)tableView:(id)arg1 cellForIndexPath:(id)arg2 ;
-(void)tableView:(id)arg1 didSelectIndexPath:(id)arg2 searchString:(id)arg3 ;
-(id)initWithItems:(id)arg1 viewController:(id)arg2 itemControllers:(id)arg3 ;
-(id)itemForIndexPath:(id)arg1 ;
-(void)pushViewController:(id)arg1 ;
-(id)init;
-(NSOrderedSet *)items;
-(unsigned)numberOfRows;
-(IGSearchResultsViewController *)viewController;
@end

