/*
* This header is generated by classdump-dyld 1.0
* on Friday, May 13, 2016 at 9:28:48 PM Central Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/6C2D6691-0360-45BF-8623-49F0546803FE/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface IGShareService : NSObject {

	char _isAvailableForSharing;
	char _wantsToShare;
	int _serviceType;

}

@property (nonatomic,readonly) int serviceType;                               //@synthesize serviceType=_serviceType - In the implementation block
@property (nonatomic,readonly) NSString * serviceNameForService; 
@property (nonatomic,readonly) char hasAdvancedOptions; 
@property (assign,nonatomic) char isAvailableForSharing;                      //@synthesize isAvailableForSharing=_isAvailableForSharing - In the implementation block
@property (nonatomic,readonly) char isAdequatelyConfigured; 
@property (assign,nonatomic) char wantsToShare;                               //@synthesize wantsToShare=_wantsToShare - In the implementation block
@property (nonatomic,readonly) char willShare; 
+(id)serviceWithType:(int)arg1 ;
-(void)setWantsToShare:(char)arg1 ;
-(char)willShare;
-(NSString *)serviceNameForService;
-(char)isAdequatelyConfigured;
-(char)hasAdvancedOptions;
-(char)wantsToShare;
-(void)setIsAvailableForSharing:(char)arg1 ;
-(char)isAvailableForSharing;
-(id)initWithServiceType:(int)arg1 ;
-(int)serviceType;
@end

