/*
* This header is generated by classdump-dyld 0.7
* on Tuesday, October 13, 2015 at 10:20:03 PM Central Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /var/mobile/Containers/Bundle/Application/095E6AAC-0201-41F1-901D-3BA0DA7A9B94/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class UIApplication;

@interface IGShortcutHandler : NSObject {

	UIApplication* _application;

}

@property (nonatomic,retain) UIApplication * application;              //@synthesize application=_application - In the implementation block
-(void)handleShortcutAction:(id)arg1 ;
-(void)setApplication:(UIApplication *)arg1 ;
-(void)dealloc;
-(void)update;
-(id)initWithApplication:(id)arg1 ;
-(UIApplication *)application;
@end

