/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, February 16, 2016 at 3:15:48 PM Central Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/C13E072C-E6C1-44DA-8A86-89C97396B2E7/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Instagram/IGChevronTitleButton.h>
#import <Instagram/IGActionSheetDelegate.h>
#import <Instagram/IGSponsorableButton.h>

@protocol IGFeedItemLoggingProviderDelegate;
@class IGFeedItem, NSMutableDictionary, NSString;

@interface IGSponsoredChevronButton : IGChevronTitleButton <IGActionSheetDelegate, IGSponsorableButton> {

	char _showIcon;
	IGFeedItem* _feedItem;
	id<IGFeedItemLoggingProviderDelegate> _loggingDelegate;
	NSMutableDictionary* _tintedColors;

}

@property (nonatomic,retain) NSMutableDictionary * tintedColors;                                        //@synthesize tintedColors=_tintedColors - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (assign,nonatomic) char showIcon;                                                             //@synthesize showIcon=_showIcon - In the implementation block
@property (nonatomic,retain) IGFeedItem * feedItem;                                                     //@synthesize feedItem=_feedItem - In the implementation block
@property (assign,nonatomic,__weak) id<IGFeedItemLoggingProviderDelegate> loggingDelegate;              //@synthesize loggingDelegate=_loggingDelegate - In the implementation block
+(id)chevronImage;
-(void)setFeedItem:(IGFeedItem *)arg1 ;
-(IGFeedItem *)feedItem;
-(void)setLoggingDelegate:(id<IGFeedItemLoggingProviderDelegate>)arg1 ;
-(void)actionSheetDismissedWithButtonTitled:(id)arg1 ;
-(void)actionSheetFinishedHiding;
-(void)setColor:(id)arg1 forState:(unsigned)arg2 ;
-(id<IGFeedItemLoggingProviderDelegate>)loggingDelegate;
-(void)updateAppearance;
-(void)onSponsoredPostLabelTapped;
-(void)setTintedColors:(NSMutableDictionary *)arg1 ;
-(NSMutableDictionary *)tintedColors;
-(id)init;
-(char)showIcon;
-(void)setShowIcon:(char)arg1 ;
@end

