/*
* This header is generated by classdump-dyld 1.0
* on Monday, February 29, 2016 at 3:36:34 PM Central Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/8E0CB1D4-3D23-4350-ABAD-ADD1AC46A9D0/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>

@interface IGStatusBarProxyViewController : UIViewController {

	char _statusBarHidden;
	int _statusBarStyle;

}

@property (assign,nonatomic) char statusBarHidden;              //@synthesize statusBarHidden=_statusBarHidden - In the implementation block
@property (assign,nonatomic) int statusBarStyle;                //@synthesize statusBarStyle=_statusBarStyle - In the implementation block
-(char)statusBarHidden;
-(int)statusBarStyle;
-(int)preferredStatusBarStyle;
-(char)prefersStatusBarHidden;
-(void)setStatusBarStyle:(int)arg1 ;
-(void)setStatusBarHidden:(char)arg1 ;
@end

