/*
* This header is generated by classdump-dyld 0.7
* on Thursday, August 27, 2015 at 8:47:17 PM Central Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /var/mobile/Containers/Bundle/Application/2DC1EEC6-8BB6-4C9F-8658-A819865606D1/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>
#import <Instagram/IGNavigationControllerDelegate.h>
#import <Instagram/IGToastViewDelegate.h>
#import <UIKit/UIGestureRecognizerDelegate.h>

@class IGTabBar, IGTabBarButton, NSArray, IGToastViewPopup, IGToastData, IGUnreadBubbleView, UIViewController, UIView, IGNavigationController, IGNewsViewController, NSString;

@interface IGTabBarController : UIViewController <IGNavigationControllerDelegate, IGToastViewDelegate, UIGestureRecognizerDelegate> {

	IGTabBar* _tabBar;
	IGTabBarButton* _homeButton;
	IGTabBarButton* _popularButton;
	IGTabBarButton* _cameraButton;
	IGTabBarButton* _newsButton;
	IGTabBarButton* _profileButton;
	char _isPerformingTabBarAction;
	NSArray* _viewControllers;
	int _selectedTabBarItem;
	IGToastViewPopup* _activityToastView;
	int _cameraButtonMode;
	IGToastData* _suppressedToastData;
	int _pendingRequestCount;
	IGUnreadBubbleView* _directUnreadBubbleView;

}

@property (nonatomic,readonly) char isTabBarVisible; 
@property (nonatomic,readonly) int selectedTabBarItem;                                         //@synthesize selectedTabBarItem=_selectedTabBarItem - In the implementation block
@property (nonatomic,readonly) UIViewController * selectedViewController; 
@property (nonatomic,readonly) NSArray * viewControllers;                                      //@synthesize viewControllers=_viewControllers - In the implementation block
@property (nonatomic,readonly) UIView * tabBar; 
@property (assign,nonatomic) char isPerformingTabBarAction;                                    //@synthesize isPerformingTabBarAction=_isPerformingTabBarAction - In the implementation block
@property (nonatomic,retain) IGToastViewPopup * activityToastView;                             //@synthesize activityToastView=_activityToastView - In the implementation block
@property (nonatomic,readonly) IGNavigationController * newsNavigationController; 
@property (nonatomic,readonly) IGNewsViewController * newsViewController; 
@property (assign,nonatomic) int cameraButtonMode;                                             //@synthesize cameraButtonMode=_cameraButtonMode - In the implementation block
@property (nonatomic,readonly) char shouldDelayToastPopup; 
@property (nonatomic,retain) IGToastData * suppressedToastData;                                //@synthesize suppressedToastData=_suppressedToastData - In the implementation block
@property (assign,nonatomic) int pendingRequestCount;                                          //@synthesize pendingRequestCount=_pendingRequestCount - In the implementation block
@property (nonatomic,retain) IGUnreadBubbleView * directUnreadBubbleView;                      //@synthesize directUnreadBubbleView=_directUnreadBubbleView - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(int)pendingRequestCount;
-(void)setPendingRequestCount:(int)arg1 ;
-(char)isTabBarVisible;
-(void)setSelectedTabBarItem:(int)arg1 animated:(char)arg2 ;
-(id)navigationControllerForTabBarItem:(int)arg1 ;
-(void)openURLInNewsTab:(id)arg1 ;
-(int)selectedTabBarItem;
-(void)prefetchAndFocusInboxInNewsTab;
-(void)inboxCountDidUpdate:(id)arg1 ;
-(void)toastCountsReceived:(id)arg1 ;
-(void)tabBarIsHiding;
-(void)popularButtonPressed;
-(void)popularButtonLongPressed:(id)arg1 ;
-(void)cameraButtonPressed;
-(void)cameraButtonLongPressed:(id)arg1 ;
-(void)newsButtonPressed;
-(void)profileButtonPressed;
-(IGNavigationController *)newsNavigationController;
-(void)logNavigationEventForClickPoint:(id)arg1 ;
-(char)itemNeedsAttention:(int)arg1 ;
-(void)hideActivityToastAnimated:(char)arg1 ;
-(char)isPerformingTabBarAction;
-(void)setIsPerformingTabBarAction:(char)arg1 ;
-(void)setNeedsAttention:(char)arg1 forItem:(int)arg2 ;
-(IGToastViewPopup *)activityToastView;
-(void)layoutToast;
-(void)hideActivityToastWithAnimation;
-(IGNewsViewController *)newsViewController;
-(char)shouldDelayToastPopup;
-(void)displaySuppressedActivityToastWhenApporiate;
-(IGToastData *)suppressedToastData;
-(void)displayActivityToastWithToastData:(id)arg1 ;
-(void)setSuppressedToastData:(IGToastData *)arg1 ;
-(char)showingActivityToast;
-(void)toastViewTapped:(id)arg1 ;
-(void)initializeViewControllersWithMainFeedSource:(id)arg1 ;
-(id)profileNavigationController;
-(IGUnreadBubbleView *)directUnreadBubbleView;
-(void)setNeedsAttentionItem:(int)arg1 ;
-(void)moveDownTabBarToOffset:(float)arg1 ;
-(void)setActivityToastView:(IGToastViewPopup *)arg1 ;
-(int)cameraButtonMode;
-(void)setCameraButtonMode:(int)arg1 ;
-(void)setDirectUnreadBubbleView:(IGUnreadBubbleView *)arg1 ;
-(void)dealloc;
-(id)init;
-(char)shouldAutorotate;
-(char)shouldAutorotateToInterfaceOrientation:(int)arg1 ;
-(id)childViewControllerForStatusBarStyle;
-(id)childViewControllerForStatusBarHidden;
-(UIView *)tabBar;
-(NSArray *)viewControllers;
-(UIViewController *)selectedViewController;
-(void)homeButtonPressed;
@end

