/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 13, 2015 at 8:03:58 PM Central Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/80FB49E7-07A3-4438-9519-37CDCDE82DE6/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Instagram/Instagram-Structs.h>
#import <Instagram/IGImageView.h>

@class NSString, IGSimpleButton;

@interface IGTappableImageView : IGImageView {

	NSString* _mediaID;
	IGSimpleButton* _button;

}

@property (nonatomic,copy) NSString * mediaID;                     //@synthesize mediaID=_mediaID - In the implementation block
@property (nonatomic,retain) IGSimpleButton * button;              //@synthesize button=_button - In the implementation block
-(NSString *)mediaID;
-(void)onButtonTapped:(id)arg1 ;
-(void)setMediaID:(NSString *)arg1 ;
-(IGSimpleButton *)button;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)setButton:(IGSimpleButton *)arg1 ;
@end

