/*
* This header is generated by classdump-dyld 0.7
* on Thursday, August 27, 2015 at 8:47:23 PM Central Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /var/mobile/Containers/Bundle/Application/2DC1EEC6-8BB6-4C9F-8658-A819865606D1/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface IGToastData : NSObject {

	unsigned _comments;
	unsigned _likes;
	unsigned _relationships;
	unsigned _userTags;
	unsigned _photosOfYou;

}

@property (assign,nonatomic) unsigned comments;                   //@synthesize comments=_comments - In the implementation block
@property (assign,nonatomic) unsigned likes;                      //@synthesize likes=_likes - In the implementation block
@property (assign,nonatomic) unsigned relationships;              //@synthesize relationships=_relationships - In the implementation block
@property (assign,nonatomic) unsigned userTags;                   //@synthesize userTags=_userTags - In the implementation block
@property (assign,nonatomic) unsigned photosOfYou;                //@synthesize photosOfYou=_photosOfYou - In the implementation block
+(id)randomTestData;
+(id)simpleTestData;
-(unsigned)photosOfYou;
-(char)isValidToShow;
-(unsigned)userTags;
-(unsigned)relationships;
-(void)setRelationships:(unsigned)arg1 ;
-(void)setUserTags:(unsigned)arg1 ;
-(void)setPhotosOfYou:(unsigned)arg1 ;
-(id)initWithDictionary:(id)arg1 ;
-(unsigned)comments;
-(void)setComments:(unsigned)arg1 ;
-(unsigned)likes;
-(void)setLikes:(unsigned)arg1 ;
@end

