/*
* This header is generated by classdump-dyld 0.7
* on Tuesday, January 19, 2016 at 3:15:00 PM Central Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/4DC55608-3697-420B-B226-BE8BA2A1BD0A/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSString;

@interface IGTwoFactorInfo : NSObject {

	NSString* _username;
	NSString* _twoFactorIdentifier;
	NSString* _obfuscatedPhoneNumber;

}

@property (nonatomic,copy) NSString * username;                           //@synthesize username=_username - In the implementation block
@property (nonatomic,copy) NSString * twoFactorIdentifier;                //@synthesize twoFactorIdentifier=_twoFactorIdentifier - In the implementation block
@property (nonatomic,copy) NSString * obfuscatedPhoneNumber;              //@synthesize obfuscatedPhoneNumber=_obfuscatedPhoneNumber - In the implementation block
-(NSString *)twoFactorIdentifier;
-(NSString *)obfuscatedPhoneNumber;
-(void)setTwoFactorIdentifier:(NSString *)arg1 ;
-(void)setObfuscatedPhoneNumber:(NSString *)arg1 ;
-(id)initWithUsername:(id)arg1 twoFactorIdentifier:(id)arg2 obfuscatedPhoneNumber:(id)arg3 ;
-(id)initWithDictionary:(id)arg1 ;
-(void)setUsername:(NSString *)arg1 ;
-(NSString *)username;
@end

