/*
* This header is generated by classdump-dyld 0.7
* on Tuesday, January 19, 2016 at 3:14:53 PM Central Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/4DC55608-3697-420B-B226-BE8BA2A1BD0A/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Instagram/IGViewController.h>
#import <UIKit/UIWebViewDelegate.h>
#import <Instagram/NJKWebViewProgressDelegate.h>
#import <Instagram/IGUnifiedWebViewToolbarDelegate.h>

@protocol UIWebViewDelegate, IGUnifiedWebViewControllerBrowsingLifeCycleDelegate, IGUnifiedWebViewControllerShareDelegate;
@class NSURLRequest, IGViewControllerTitleDetailTitleView, UIWebView, NJKWebViewProgress, UIProgressView, IGUnifiedWebViewToolbar, NSMutableSet, IGTableViewInsetInfoView, NSString;

@interface IGUnifiedWebViewController : IGViewController <UIWebViewDelegate, NJKWebViewProgressDelegate, IGUnifiedWebViewToolbarDelegate> {

	char _shareButtonVisible;
	char _navigationToolBarEnabled;
	id<UIWebViewDelegate> _webViewDelegate;
	id<IGUnifiedWebViewControllerBrowsingLifeCycleDelegate> _browsingDelegate;
	id<IGUnifiedWebViewControllerShareDelegate> _shareDelegate;
	unsigned _titleViewType;
	unsigned _titleTextType;
	NSURLRequest* _urlRequest;
	IGViewControllerTitleDetailTitleView* _titleView;
	UIWebView* _webView;
	NJKWebViewProgress* _webViewProgress;
	UIProgressView* _progressView;
	IGUnifiedWebViewToolbar* _navigationToolBar;
	NSMutableSet* _webViewLoggers;
	IGTableViewInsetInfoView* _infoView;

}

@property (assign,nonatomic,__weak) id<UIWebViewDelegate> webViewDelegate;                                                 //@synthesize webViewDelegate=_webViewDelegate - In the implementation block
@property (assign,nonatomic,__weak) id<IGUnifiedWebViewControllerBrowsingLifeCycleDelegate> browsingDelegate;              //@synthesize browsingDelegate=_browsingDelegate - In the implementation block
@property (assign,nonatomic,__weak) id<IGUnifiedWebViewControllerShareDelegate> shareDelegate;                             //@synthesize shareDelegate=_shareDelegate - In the implementation block
@property (nonatomic,readonly) unsigned titleViewType;                                                                     //@synthesize titleViewType=_titleViewType - In the implementation block
@property (nonatomic,readonly) unsigned titleTextType;                                                                     //@synthesize titleTextType=_titleTextType - In the implementation block
@property (nonatomic,readonly) char shareButtonVisible;                                                                    //@synthesize shareButtonVisible=_shareButtonVisible - In the implementation block
@property (nonatomic,readonly) char navigationToolBarEnabled;                                                              //@synthesize navigationToolBarEnabled=_navigationToolBarEnabled - In the implementation block
@property (nonatomic,copy,readonly) NSURLRequest * urlRequest;                                                             //@synthesize urlRequest=_urlRequest - In the implementation block
@property (nonatomic,retain) IGViewControllerTitleDetailTitleView * titleView;                                             //@synthesize titleView=_titleView - In the implementation block
@property (nonatomic,retain) UIWebView * webView;                                                                          //@synthesize webView=_webView - In the implementation block
@property (nonatomic,retain) NJKWebViewProgress * webViewProgress;                                                         //@synthesize webViewProgress=_webViewProgress - In the implementation block
@property (nonatomic,retain) UIProgressView * progressView;                                                                //@synthesize progressView=_progressView - In the implementation block
@property (nonatomic,retain) IGUnifiedWebViewToolbar * navigationToolBar;                                                  //@synthesize navigationToolBar=_navigationToolBar - In the implementation block
@property (nonatomic,retain) NSMutableSet * webViewLoggers;                                                                //@synthesize webViewLoggers=_webViewLoggers - In the implementation block
@property (nonatomic,retain) IGTableViewInsetInfoView * infoView;                                                          //@synthesize infoView=_infoView - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithURLRequest:(id)arg1 titleViewType:(unsigned)arg2 titleTextType:(unsigned)arg3 shareButtonVisible:(char)arg4 navigationToolBarEnabled:(char)arg5 ;
-(void)setBrowsingDelegate:(id<IGUnifiedWebViewControllerBrowsingLifeCycleDelegate>)arg1 ;
-(void)addWebViewLogger:(id)arg1 ;
-(void)setNavigationBarTitle:(id)arg1 forURL:(id)arg2 ;
-(NJKWebViewProgress *)webViewProgress;
-(void)webViewProgress:(id)arg1 didUpdateProgress:(float)arg2 ;
-(void)setWebViewProgress:(NJKWebViewProgress *)arg1 ;
-(void)configureForWhiteColorScheme;
-(unsigned)titleTextType;
-(id<IGUnifiedWebViewControllerBrowsingLifeCycleDelegate>)browsingDelegate;
-(char)shareButtonVisible;
-(void)shareBarButtonTapped:(id)arg1 ;
-(NSMutableSet *)webViewLoggers;
-(char)navigationToolBarEnabled;
-(IGUnifiedWebViewToolbar *)navigationToolBar;
-(void)setNavigationToolBar:(IGUnifiedWebViewToolbar *)arg1 ;
-(void)networkErrorInfoViewRefreshButtonWasTapped:(id)arg1 ;
-(id<IGUnifiedWebViewControllerShareDelegate>)shareDelegate;
-(id<UIWebViewDelegate>)webViewDelegate;
-(void)presentToolbar;
-(void)presentNetworkErrorInfoView;
-(unsigned)titleViewType;
-(void)webViewToolbarBackButtonTapped:(id)arg1 ;
-(void)webViewToolbarForwardButtonTapped:(id)arg1 ;
-(void)setWebViewDelegate:(id<UIWebViewDelegate>)arg1 ;
-(void)setShareDelegate:(id<IGUnifiedWebViewControllerShareDelegate>)arg1 ;
-(void)setWebViewLoggers:(NSMutableSet *)arg1 ;
-(IGTableViewInsetInfoView *)infoView;
-(void)setInfoView:(IGTableViewInsetInfoView *)arg1 ;
-(char)respondsToSelector:(SEL)arg1 ;
-(void)setTitle:(id)arg1 ;
-(int)preferredStatusBarStyle;
-(IGViewControllerTitleDetailTitleView *)titleView;
-(void)setTitleView:(IGViewControllerTitleDetailTitleView *)arg1 ;
-(id)forwardingTargetForSelector:(SEL)arg1 ;
-(void)viewWillAppear:(char)arg1 ;
-(void)viewDidLoad;
-(void)viewDidAppear:(char)arg1 ;
-(void)viewDidDisappear:(char)arg1 ;
-(char)automaticallyAdjustsScrollViewInsets;
-(UIWebView *)webView;
-(void)setWebView:(UIWebView *)arg1 ;
-(void)webView:(id)arg1 didFailLoadWithError:(id)arg2 ;
-(char)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(int)arg3 ;
-(void)webViewDidStartLoad:(id)arg1 ;
-(void)webViewDidFinishLoad:(id)arg1 ;
-(void)setProgressView:(UIProgressView *)arg1 ;
-(UIProgressView *)progressView;
-(NSURLRequest *)urlRequest;
@end

