/*
* This header is generated by classdump-dyld 1.0
* on Monday, April 11, 2016 at 7:41:46 PM Central Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /private/var/mobile/Containers/Bundle/Application/F2F7650E-6416-4D13-A52F-83DEE7C62D71/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMutableArray;

@interface IGVisitedRelatedItemsStore : NSObject {

	NSMutableArray* _visitedItems;

}

@property (nonatomic,retain) NSMutableArray * visitedItems;              //@synthesize visitedItems=_visitedItems - In the implementation block
+(id)sharedHashtagsStore;
+(id)sharedLocationsStore;
-(void)addVisitedItem:(id)arg1 ;
-(id)allVisitedItems;
-(NSMutableArray *)visitedItems;
-(void)setVisitedItems:(NSMutableArray *)arg1 ;
-(id)init;
@end

