/*
* This header is generated by classdump-dyld 0.7
* on Monday, October 26, 2015 at 9:24:44 PM Central Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/21A1C6E8-DEFC-46E0-A287-C60E9807B6FE/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Instagram/IGFindFriendsHelperProtocol.h>

@protocol IGFindFriendsHelperDelegate;
@class UIViewController, NSString;

@interface IGVKFriendsHelper : NSObject <IGFindFriendsHelperProtocol> {

	UIViewController*<IGFindFriendsHelperDelegate> _delegate;

}

@property (assign,nonatomic,__weak) UIViewController*<IGFindFriendsHelperDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)authorizeAndFetchUsers;
-(void)onVkontakteAuthSuccessDismissOAuth:(char)arg1 ;
-(void)onVkontakteAuthSuccess;
-(void)onVkontakteAuthFailure;
-(void)setDelegate:(UIViewController*<IGFindFriendsHelperDelegate>)arg1 ;
-(void)dealloc;
-(UIViewController*<IGFindFriendsHelperDelegate>)delegate;
@end

