/*
* This header is generated by classdump-dyld 0.7
* on Monday, October 26, 2015 at 9:24:46 PM Central Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/21A1C6E8-DEFC-46E0-A287-C60E9807B6FE/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Instagram/IGWeiboAuthDelegate.h>
#import <Instagram/IGServiceHelperProtocol.h>

@class NSString;

@interface IGWeiboHelper : NSObject <IGWeiboAuthDelegate, IGServiceHelperProtocol> {

	NSString* _accessToken;
	NSString* _refreshToken;

}

@property (nonatomic,readonly) char accessTokenExpired; 
@property (nonatomic,copy) NSString * accessToken;                       //@synthesize accessToken=_accessToken - In the implementation block
@property (nonatomic,copy) NSString * refreshToken;                      //@synthesize refreshToken=_refreshToken - In the implementation block
@property (nonatomic,readonly) NSString * serviceName; 
@property (nonatomic,readonly) NSString * shortServiceName; 
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)sharedHelper;
-(id)sharingInfo;
-(void)logoutAndUnlink;
-(char)isConfigurable;
-(char)hasAdvancedOptions;
-(char)requiresLocationCoordinate;
-(char)hasEverBeenConfigured;
-(char)isAvailableInCurrentLocale;
-(char)supportsMediaType:(int)arg1 ;
-(NSString *)shortServiceName;
-(char)needsToReauthorize;
-(void)reauthorizeIfNeeded;
-(id)viewControllerForAdvancedOptions;
-(id)authURLString;
-(id)callbackURLString;
-(void)reauthorize;
-(void)weiboAuthControllerLoginFailed:(id)arg1 ;
-(void)weiboAuthController:(id)arg1 didLoginWithAccessToken:(id)arg2 andRefreshToken:(id)arg3 ;
-(id)serviceNameForTokenStore;
-(char)accessTokenExpired;
-(void)saveAccessToken:(id)arg1 andRefreshToken:(id)arg2 ;
-(int)tokenLife;
-(void)saveNewAccessToken:(id)arg1 ;
-(void)saveNewRefreshToken:(id)arg1 ;
-(NSString *)serviceName;
-(void)setRefreshToken:(NSString *)arg1 ;
-(NSString *)refreshToken;
-(NSString *)accessToken;
-(void)logout;
-(id)clientID;
-(void)setAccessToken:(NSString *)arg1 ;
-(char)isConfigured;
@end

