/*
* This header is generated by classdump-dyld 0.7
* on Monday, October 26, 2015 at 9:24:50 PM Central Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/21A1C6E8-DEFC-46E0-A287-C60E9807B6FE/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Instagram/Instagram-Structs.h>
#import <Instagram/TBaseStruct.h>
#import <Instagram/TBase.h>
#import <libobjc.A.dylib/NSCoding.h>

@class NSString, NSMutableArray;

@interface MarauderEventBatch : TBaseStruct <TBase, NSCoding> {

	long long __thrift_timeStampInMilliseconds;
	NSString* __thrift_deviceID;
	NSString* __thrift_appID;
	NSString* __thrift_appVersion;
	NSMutableArray* __thrift_events;
	NSString* __thrift_platformSoftwareVersion;
	NSString* __thrift_platformHardwareVersion;
	char __thrift_timeStampInMilliseconds_set;
	char __thrift_deviceID_set;
	char __thrift_appID_set;
	char __thrift_appVersion_set;
	char __thrift_events_set;
	char __thrift_platformSoftwareVersion_set;
	char __thrift_platformHardwareVersion_set;

}

@property (assign,nonatomic) long long timeStampInMilliseconds; 
@property (nonatomic,retain) NSString * deviceID; 
@property (nonatomic,retain) NSString * appID; 
@property (nonatomic,retain) NSString * appVersion; 
@property (nonatomic,retain) NSMutableArray * events; 
@property (nonatomic,retain) NSString * platformSoftwareVersion; 
@property (nonatomic,retain) NSString * platformHardwareVersion; 
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)setPlatformSoftwareVersion:(NSString *)arg1 ;
-(void)setPlatformHardwareVersion:(NSString *)arg1 ;
-(id)toDict;
-(void)read:(id)arg1 ;
-(void)setTimeStampInMilliseconds:(long long)arg1 ;
-(long long)timeStampInMilliseconds;
-(char)timeStampInMillisecondsIsSet;
-(void)unsetTimeStampInMilliseconds;
-(id)initWithTimeStampInMilliseconds:(long long)arg1 deviceID:(id)arg2 appID:(id)arg3 appVersion:(id)arg4 events:(NSMutableArray*)arg5 platformSoftwareVersion:(id)arg6 platformHardwareVersion:(id)arg7 ;
-(char)deviceIDIsSet;
-(void)unsetDeviceID;
-(char)appIDIsSet;
-(void)unsetAppID;
-(char)appVersionIsSet;
-(void)unsetAppVersion;
-(char)eventsIsSet;
-(void)unsetEvents;
-(NSString *)platformSoftwareVersion;
-(char)platformSoftwareVersionIsSet;
-(void)unsetPlatformSoftwareVersion;
-(NSString *)platformHardwareVersion;
-(char)platformHardwareVersionIsSet;
-(void)unsetPlatformHardwareVersion;
-(char)makeImmutable;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(id)init;
-(NSString *)description;
-(id)mutableCopyWithZone:(NSZone*)arg1 ;
-(void)validate;
-(void)write:(id)arg1 ;
-(void)setAppID:(NSString *)arg1 ;
-(void)setDeviceID:(NSString *)arg1 ;
-(void)setEvents:(NSMutableArray *)arg1 ;
-(NSString *)deviceID;
-(NSString *)appVersion;
-(void)setAppVersion:(NSString *)arg1 ;
-(NSMutableArray *)events;
-(NSString *)appID;
@end

