/*
* This header is generated by classdump-dyld 0.7
* on Tuesday, September 15, 2015 at 5:29:46 PM Central Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /var/mobile/Containers/Bundle/Application/78EC956B-7ED8-4B50-8025-C2B1976EEC28/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class OAMutableURLRequest, NSURLResponse, NSData, NSString;

@interface OAServiceTicket : NSObject {

	OAMutableURLRequest* request;
	NSURLResponse* response;
	NSData* data;
	int responseCode;
	char didSucceed;

}

@property (readonly) OAMutableURLRequest * request; 
@property (readonly) NSURLResponse * response; 
@property (readonly) NSData * data; 
@property (readonly) int responseCode; 
@property (readonly) char didSucceed; 
@property (readonly) NSString * body; 
-(id)initWithRequest:(id)arg1 response:(id)arg2 data:(id)arg3 didSucceed:(char)arg4 responseCode:(int)arg5 ;
-(int)responseCode;
-(char)didSucceed;
-(void)dealloc;
-(OAMutableURLRequest *)request;
-(NSData *)data;
-(NSString *)body;
-(NSURLResponse *)response;
@end

