/*
* This header is generated by classdump-dyld 1.0
* on Monday, February 29, 2016 at 3:36:44 PM Central Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/8E0CB1D4-3D23-4350-ABAD-ADD1AC46A9D0/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIButton.h>

@class IGQuadtreeCluster, IGPhotoMapEditManager;

@interface PhotoMapReviewClusterSelectButton : UIButton {

	IGQuadtreeCluster* _cluster;
	IGPhotoMapEditManager* _editManager;

}

@property (nonatomic,retain) IGQuadtreeCluster * cluster;                      //@synthesize cluster=_cluster - In the implementation block
@property (nonatomic,retain) IGPhotoMapEditManager * editManager;              //@synthesize editManager=_editManager - In the implementation block
+(id)buttonWithType:(int)arg1 cluster:(id)arg2 editManager:(id)arg3 ;
-(IGPhotoMapEditManager *)editManager;
-(void)setEditManager:(IGPhotoMapEditManager *)arg1 ;
-(void)onClusterSelectionChanged;
-(void)dealloc;
-(void)setCluster:(IGQuadtreeCluster *)arg1 ;
-(IGQuadtreeCluster *)cluster;
@end

