/*
* This header is generated by classdump-dyld 1.0
* on Friday, May 13, 2016 at 9:28:39 PM Central Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/6C2D6691-0360-45BF-8623-49F0546803FE/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface POPAnimationEvent : NSObject {

	unsigned _type;
	NSString* _animationDescription;
	double _time;

}

@property (nonatomic,copy) NSString * animationDescription;              //@synthesize animationDescription=_animationDescription - In the implementation block
@property (nonatomic,readonly) unsigned type;                            //@synthesize type=_type - In the implementation block
@property (nonatomic,readonly) double time;                              //@synthesize time=_time - In the implementation block
-(void)_appendDescription:(id)arg1 ;
-(NSString *)animationDescription;
-(id)initWithType:(unsigned)arg1 time:(double)arg2 ;
-(void)setAnimationDescription:(NSString *)arg1 ;
-(id)description;
-(unsigned)type;
-(double)time;
@end

