/*
* This header is generated by classdump-dyld 0.7
* on Thursday, August 27, 2015 at 8:51:39 PM Central Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /var/mobile/Containers/Bundle/Application/2DC1EEC6-8BB6-4C9F-8658-A819865606D1/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Instagram/Instagram-Structs.h>
#import <Instagram/POPAnimation.h>

@interface POPCustomAnimation : POPAnimation {

	/*^block*/id _animate;
	double _currentTime;
	double _elapsedTime;

}

@property (nonatomic,readonly) double currentTime;              //@synthesize currentTime=_currentTime - In the implementation block
@property (nonatomic,readonly) double elapsedTime;              //@synthesize elapsedTime=_elapsedTime - In the implementation block
@property (nonatomic,copy) id animate;                          //@synthesize animate=_animate - In the implementation block
+(id)animationWithBlock:(/*^block*/id)arg1 ;
-(void)_appendDescription:(id)arg1 debug:(char)arg2 ;
-(char)_advance:(id)arg1 currentTime:(double)arg2 elapsedTime:(double)arg3 ;
-(id)_init;
-(id)copyWithZone:(NSZone*)arg1 ;
-(double)beginTime;
-(id)animate;
-(double)elapsedTime;
-(double)currentTime;
-(void)setAnimate:(id)arg1 ;
@end

