/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 26, 2016 at 3:43:38 PM Central Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /private/var/mobile/Containers/Bundle/Application/5A2897A0-78CA-4D27-9EEF-4F1B698EB436/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UINavigationController.h>
#import <UIKit/UINavigationBarDelegate.h>

@class NSString;

@interface RCTNavigationController : UINavigationController <UINavigationBarDelegate> {

	/*^block*/id _scrollCallback;
	unsigned _navigationLock;

}

@property (assign,nonatomic) unsigned navigationLock;               //@synthesize navigationLock=_navigationLock - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(unsigned)navigationLock;
-(void)setNavigationLock:(unsigned)arg1 ;
-(id)initWithScrollCallback:(/*^block*/id)arg1 ;
-(char)navigationBar:(id)arg1 shouldPopItem:(id)arg2 ;
@end

