/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 26, 2016 at 3:43:38 PM Central Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /private/var/mobile/Containers/Bundle/Application/5A2897A0-78CA-4D27-9EEF-4F1B698EB436/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Instagram/RCTShadowView.h>
#import <Instagram/RCTImageComponent.h>

@class RCTBridge, UIImage, RCTImageSource, NSString;

@interface RCTShadowVirtualImage : RCTShadowView <RCTImageComponent> {

	RCTBridge* _bridge;
	/*^block*/id _cancellationBlock;
	UIImage* _image;
	RCTImageSource* _source;
	int _resizeMode;

}

@property (nonatomic,retain) RCTImageSource * source;               //@synthesize source=_source - In the implementation block
@property (assign,nonatomic) int resizeMode;                        //@synthesize resizeMode=_resizeMode - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,readonly) UIImage * image;                     //@synthesize image=_image - In the implementation block
-(id)initWithBridge:(id)arg1 ;
-(void)didSetProps:(id)arg1 ;
-(int)resizeMode;
-(void)dealloc;
-(id)init;
-(UIImage *)image;
-(RCTImageSource *)source;
-(void)setSource:(RCTImageSource *)arg1 ;
-(void)setResizeMode:(int)arg1 ;
@end

