/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, February 16, 2016 at 3:16:01 PM Central Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/C13E072C-E6C1-44DA-8A86-89C97396B2E7/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <CoreFoundation/NSException.h>

@interface TException : NSException
+(id)exceptionWithName:(id)arg1 reason:(id)arg2 ;
+(id)exceptionWithName:(id)arg1 reason:(id)arg2 error:(id)arg3 ;
+(id)exceptionWithName:(id)arg1 ;
-(id)description;
@end

