/*
* This header is generated by classdump-dyld 0.7
* on Tuesday, October 6, 2015 at 9:46:14 PM Central Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /var/mobile/Containers/Bundle/Application/E660306A-8A68-4027-9100-A800454451FF/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <CoreFoundation/NSException.h>

@interface TException : NSException
+(id)exceptionWithName:(id)arg1 reason:(id)arg2 ;
+(id)exceptionWithName:(id)arg1 reason:(id)arg2 error:(id)arg3 ;
+(id)exceptionWithName:(id)arg1 ;
-(id)description;
@end

